### ISSUE TITLE
"Could not authenticate with OAuth"

### ISSUE THREAD

**Issue by kjeldoostra** [themattharris/tmhOAuth#10]
Hi,

First of all, I'd like to say that your OAuth lib is definitely the most user-friendly. However, I stumbled upon a (perhaps small) issue. I used your 'tweet.php' example to tweet a message with the following code:

<?php

require 'tmh/tmhOAuth.php';
require 'tmh/tmhUtilities.php';
$tmhOAuth = new tmhOAuth(array(
        'consumer_key'               => 'XXXXXXXXXXX',
        'consumer_secret'            => 'XXXXXXXXXXXXXXXXXXXXXX',
        'user_token'                 => 'XXXX-XXXXXXXXXXXXXXXXXXX',
        'user_secret'                => 'XXXXXXXXXXXXXXXXXXXXXX'));

$code = $tmhOAuth->request('POST', $tmhOAuth->url('1/statuses/update'), array('status' => 'My Twitter Message'));

tmhUtilities::pr(json_decode($tmhOAuth->response['response']));

?>

I also created an app at dev.twitter.com and filled in all fields with the data on that page (consumer_key = Consumer Key, consumer_secret = Consumer Secret, user_token = Access Token, user_secret = Access Token Secret).

When I load the page, I get the following error message;

stdClass Object
(
    [error] => Could not authenticate with OAuth.
    [request] => /1/statuses/update.json
)

What's wrong here?

Thanks in advance, and keep up the good work!

-Kjeld

**Comment by themattharris** [comment]
Hi Kjeld,

Thanks for the kind words, it's great to know the library is easy to use.
The error that's coming back indicates that the Twitter API believes the OAuth credentials you have passed are no longer valid. This can happen for a couple of reasons:
- if the user either revokes an applications access to act on their behalf the tokens will no longer be valid
- if the user has reauthorised the application at a permission level different to the level the tokens were originally issued at
- the user account is longer valid (maybe deleted).

Double check the user_token and user_secret values you copied in are correct. If you're not sure what they are you can obtain them by going through the OAuth authorization process again.

Let me know how it goes,
@themattharris

**Comment by kjeldoostra** [comment]
Hi Matt Harris,

Thank you for your reply. I copied the user_token (Access Token) and user_token_secret (Access Token Secret) directly from the My Applications page at dev.twitter.com. I don't need any other users to use my application, so the tokens at the My Applications page are the only tokens I need I assume. I have double checked the tokens in the PHP file, they match exactly with the tokens on the My Applications page. Since it is my application and it is in my Settings/Applications list of authorized applications, I don't think the application's access is revoked. Are the tokens at the My Applications page the tokens I need to use, or do I need to use other tokens?

Looking forward to your reply,

-Kjeld

**Comment by kjeldoostra** [comment]
I just see I accidentally closed this, but now it's open again :)

**Comment by themattharris** [comment]
This seems like an issue with the My Access Tokens on dev.twitter.com and not an issue with the library. My recommendation is to open this up as a discussion on https://dev.twitter.com/discussions to see if anyone else is having the issue. I can also follow up with my Twitter hat on then and look into it.

When you've started the conversation on dev.twitter.com can you post the link as a reply to this thread and then close the issue here (as it isn't anything with the library)?

**Comment by kjeldoostra** [comment]
Righto, here's the link to the discussion;
https://dev.twitter.com/discussions/305

Closing this thread now.
