### ISSUE TITLE
helpme Retrieving Direct Messages

### ISSUE THREAD

**Issue by tianbellmann** [themattharris/tmhOAuth#101]
I can not read the private messages ..

the souce is...

```
$tmhOAuth = new tmhOAuth(array(        'consumer_key' => 'xxxxxxxxxxxx',        'consumer_secret' => xxxxxxxxxxxxxx',        'user_token' => 'xxxxxxxxxxxxxx',        'user_secret' => 'xxxxxxxxxxxxxx'    ));
```

$code = $tmhOAuth->request('GET', $tmhOAuth->url('1.1/direct_messages.json'), array(  'count' => 1,  'page' => 1 ) );

echo $code;

I can not get any message

the aplication have permission is activated 

Access level    Read, write, and direct messages

**Comment by themattharris** [comment]
what response code do you get back from the Twitter API when requesting this URL? if you can share the contents of `$tmhOAuth->response['raw']` here it will aid with debugging what's happening. (if the direct message content is returned and visible, don't include it in the paste).
