### ISSUE TITLE
Reading new filtered stream stops different filtered stream

### ISSUE THREAD

**Issue by thenetimp** [themattharris/tmhOAuth#103]
I have a project that requires me to filter 3 hashtags in different processes.  When I start my script the first time it runs.  When I start it the 2nd time it stops the first process.  If I start the 3rd it stops the 2nd process.

Why does the streaming of one process affect the streaming of another?

**Comment by themattharris** [comment]
i'm assuming you are using the same credentials when connecting to the Streaming API. Twitter only allows one connection to the Streaming API for each account (ref: https://dev.twitter.com/docs/streaming-apis/streams/public#Connections)
