### ISSUE TITLE
CURLOPT error

### ISSUE THREAD

**Issue by ArnalOMallet** [themattharris/tmhOAuth#104]
Hi.

Ive updated my PHP version to PHP5 but I still have this error:

Warning: curl_setopt_array() [function.curl-setopt-array]: Array keys must be CURLOPT constants or equivalent interger values. in /mnt/159/sdb/e/3/arnaud.mallet50/tweetershell/tmhOAuth.php on line 606

How can I resolved it ? 

Thanks for your help

**Comment by themattharris** [comment]
what version of PHP5 did you install?
also, do you have safe_mode or open_basedir configured? 

`<?php php_info(); ?>`

 should be able to tell you the answers to those questions

**Comment by ArnalOMallet** [comment]
Version : 5.1.3
safe_mode : On
open_basedir : No value

**Comment by themattharris** [comment]
ok, so safe_mode being on is very likely to be the cause of the issue. i'm referencing the comments here: http://php.net/manual/en/features.safe-mode.functions.php -- and many other sources --  which say `curl_setopt(CURLOPT_FOLLOWLOCATION ...` cannot be used in safe_mode.

from http://php.net/manual/en/features.safe-mode.php safe_mode is deprecated in PHP 5.3.0 and removed in PHP 5.4.0 -- so i'm not comfortable removing that `curl_setopt` setting from the library.

have you considered turning off safe_mode for your installation?

**Comment by ArnalOMallet** [comment]
I cant modify PHP options with my FTP host. Is it possible to overide safe_mode option using htaccess file for example?

**Comment by maximal** [comment]
> Is it possible to overide safe_mode option using htaccess file for example?

Unfortunately no. Or fortunately :-)

**Comment by themattharris** [comment]
this is an issue with the configuration of the server you are using. while it's possible to remove the CURLOPT_FOLLOWLOCATION setting it isn't something i'm comfortable doing to the main library.

if you wish to comment out that line to see if things work please go ahead, but know that redirects won't be followed by the library anymore.
