### ISSUE TITLE
Expectation Failed Issue 417

### ISSUE THREAD

**Issue by LeagueRivals** [themattharris/tmhOAuth#105]
Hi Matt, 

My code was working fine before (posting images) however it suddenly doesn't? I've not updated the php code for several months now? I've got the following 417 error on the page. Any help would be appreciated. 

Expectation Failed

The expectation given in the Expect request-header field could not be met by this server.

The client sent

```
Expect: 100-continue
```

but we only allow the 100-continue expectation.

**Comment by LeagueRivals** [comment]
Sorted the Issue 417 problem above with the following code on line 651 of the tmhOAuth file (I don't know if it's in the correct place?):

curl_setopt($c, CURLOPT_HTTPHEADER, array('Expect:'));

However I now have the following error showing up:

{"request":"\/1\/statuses\/update_with_media.json","error":"Could not authenticate you."}

I've looked back through the older issues with no luck. Any ideas Matt?

Thanks again.

**Comment by LeagueRivals** [comment]
Problem solved. I added $this->headers['Expect'] = ''; to line 357 in tmhoauth.php and it worked.

**Comment by sourabhmkhrj46** [comment]
Hello,

I was facing the same issue.
Then i looked into the Solved Issues section in GitHub and found your post.
My issue is solved.
Thanks you saved me a lot of time.

Sincerely,
Sourav Mukherjee

**Comment by themattharris** [comment]
wanted to follow up on this to say that the Twitter API looks to have fixed the issue that required the `$this->headers['Expect'] = '';` hack to be set. if you have this in your scripts, or modified tmhOAuth to set it, please remove it. it's invalid to have an empty expects header in a request.
