### ISSUE TITLE
How to start userstream from browser?

### ISSUE THREAD

**Issue by schip1978** [themattharris/tmhOAuth#107]
Hi there, 

I understand the stream is a long lasting php-reqeust. Now for my application I want to use the userstream to store tweets in a database. 

The stream should be started via a function call. (I'm developing a Joomla component), however, it doesnot seem to work. 

How do "start" the userstream script from a function, e.g. without cli ?

thnx for your support,
Paul

**Comment by themattharris** [comment]
the library doesn't really care about how it's invoked, but, as streaming connections are long running, you don't want to lock up your web serving threads with an open connection to the Twitter streaming API.

there are a number of ways you could do this but you should probably detach the joomla action component from the process of starting the streaming connection.

put another way, the code that starts the streaming connection is better off not being part of the joomla component - and instead the component sets a value in a database which is then seen by some cron job that polls your system for that value. when the cron job sees that value, it runs exec to begin a userstream connection.
