### ISSUE TITLE
update_with_media don't work

### ISSUE THREAD

**Issue by formariz** [themattharris/tmhOAuth#108]
Guys, the exemple don't work for me.
Please, help me.

My code PHP

``` php
require '../tmhOAuth.php';
require '../tmhUtilities.php';
$tmhOAuth = new tmhOAuth(array(
  'consumer_key'    => '***************',
  'consumer_secret' => '***************',
  'user_token'      => '***************',
  'user_secret'     => '***************',
));

$image = 'sol.jpg';

$code = $tmhOAuth->request(
  'POST',
  'https://api.twitter.com/1.1/statuses/update_with_media.json',
  array(
    'media[]'  => "@{$image};type=image/jpeg;filename={$image}",
    'status'   => 'Picture time'
  ),
  true,
  true
);

var_dump($tmhOAuth->response);

if ($code == 200) {
  tmhUtilities::pr(json_decode($tmhOAuth->response['response']));
} else {
  tmhUtilities::pr($tmhOAuth->response['response']);
}
```

And response

``` javascript
array(6) {
    ["raw"]=> string(0) ""
    ["code"]=> int(0)
    ["response"]=> bool(false)
    ["info"]=> array(22) {
        ["url"]=> string(62) "https://api.twitter.com/1.1/statuses/update_with_media.json"
        ["content_type"]=> NULL
        ["http_code"]=> int(0)
        ["header_size"]=> int(0)
        ["request_size"]=> int(0)
        ["filetime"]=> int(-1)
        ["ssl_verify_result"]=> int(0)
        ["redirect_count"]=> int(0)
        ["total_time"]=> float(0.936)
        ["namelookup_time"]=> float(0)
        ["connect_time"]=> float(0.281)
        ["pretransfer_time"]=> float(0.936)
        ["size_upload"]=> float(0)
        ["size_download"]=> float(0)
        ["speed_download"]=> float(0)
        ["speed_upload"]=> float(0)
        ["download_content_length"]=> float(-1)
        ["upload_content_length"]=> float(-1)
        ["starttransfer_time"]=> float(0)
        ["redirect_time"]=> float(0)
        ["certinfo"]=> array(0) { }
        ["redirect_url"]=> string(0) "" 
    }
    ["error"]=> string(29) "couldn't open file "sol.jpg" "
    ["errno"]=> int(26)
}
```

Any idea?

**Comment by samhenry** [comment]
I just figured out how to get this working for one of my own scripts. I'm using the latest version of tmhOauth at the time of this post. Here's the gist of what I did:

``` php
$tmhOAuth->config['host'] = 'upload.twitter.com'; //Change the host
$url = '1.1/statuses/update_with_media'; //Set the endpoint url
$imagefullpath = '/home/user/dir/image.jpg'; //Use a full, local path to the image being posted

$parameters['media[]'] = "@{$imagefullpath}"; //Set the media parameter
$parameters['status'] = "Tweet text"; //Set the status parameter

$tmhOAuth->request('POST', $tmhOAuth->url($url), $parameters, true, true); //Make the request
```

The most important part for me was using a "full path" to the image. tmhOauth uses CURLOPT_POSTFIELDS to post this and the PHP docs on setting cURL options mentions using full paths. See http://docs.php.net/function.curl-setopt

**Comment by wiresfj** [comment]
Yep that worked for me.... happy days. Thank you for sharing the info.

**Comment by themattharris** [comment]
hey guys, you should be hitting `$tmhOAuth->url('1.1/statuses/update_with_media');` with `$tmhOAuth->config['host'] = 'api.twitter.com'` (the default). in API v1.1. twitter moved to hosting all URLs on api.twitter.com - so the host name of `upload.twitter.com` is no longer recommended.

@formariz your original issue was erroring because you didn't provide the full path to the image file. what you want to do is instead of `$image = 'sol.jpg';` do something like `$image = dirname(__FILE__) . DIRECTORY_SEPARATOR . 'sol.jpg'` and put the file sol.jpg in the same folder as your PHP script.

**Comment by formariz** [comment]
@themattharris  Thanks for reply.
My file is in the same directory as the script.
I need to change this call?

**Comment by themattharris** [comment]
@formariz i see you got my other comment in Issue #76. i'll close this ticket out as it sounds like you've got things working from the advice in that issue.
