### ISSUE TITLE
Getting followers/ids from users with more than 75000 followers rate limit problem

### ISSUE THREAD

**Issue by oosswwaalldd** [themattharris/tmhOAuth#109]
Hi Matt,

the problem with the new API v1.1 I found with my app is that everyday I need to check the list of followers (all the followers) of my authenticated users in my app, with the new version of the API, because of the 15 API calls per 15 minutes window limit, my script will only grabs 75000 followers for that user (15 times the max amount of ids per cursor [5000]), so the question is,

how can I get all the followers from a user if this users exceeds 75000 followers?

should I store the cursor from the last followers/ids call?

are those cursors static? do they change between API calls?

Is there a workaround in your lib to fetch all followers ids from a user who has more that 75000 followers, without having to wait the 15 minutes window reset?

I need help in this matter please because I dont want any kind of problems with the new implementation of this API and my users.

Thanks a lot!

**Comment by themattharris** [comment]
tmhOAuth can only do what the Twitter API offers and allows. for enumerating the 75000 followers an account has it would be better to gather all the followers at the pace the rate limit allows, and then stay current with the follower/following list using something like userstreams or site streams (assuming the user has granted you permission to operate on their behalf).
