### ISSUE TITLE
User Lookup returning Error after a few attempts

### ISSUE THREAD

**Issue by ankitagarwal** [themattharris/tmhOAuth#11]
Am not sure whats the issue..but I have spend hours trying to figure out what exactly is going wrong...
I am using user/lookup with multiple user_ids.. everything goes fine during the first few attempts..but when I loop through it more than 6-7 times following errors start popping up
"code":18,"message":"Too many terms specified in query"

any suggestions will be appreciated.
Thanks

**Comment by ankitagarwal** [comment]
Sorry My bad..stupid issue on my side..wasted 5 hours on a dumb mistake :(

**Comment by themattharris** [comment]
No worries. Thanks for updating the issue. Out of interest what were you doing wrong? Maybe I can add a comment to the code?

**Comment by ankitagarwal** [comment]
well I was adding user_ids in a loop..and didnt unset the array in the start of the loop..so after a few loop..the array size was way more than 100.. :)

**Comment by optionsninja** [comment]
Matt, 

Thanks for writing this code. 

I have a similar problem as above, unfortunately I can't seem to figure it out. Although, I do believe that my problem lies some where with the $paging variable. 

This is the front part of the loop: 

```
$paging = ceil(count($ids) / PAGESIZE);
echo "this is paging " . $paging . "\n";
$users = array();
$x=0;
for ($i=0; $i < $paging ; $i++) 
    {
        $set = array_slice($ids, $i*PAGESIZE, PAGESIZE);
        $tmhOAuth->request('GET', $tmhOAuth->url('1/users/lookup'), array(
        'user_id' => implode(',', $set)
         ));
// check the rate limit
  check_rate_limit($tmhOAuth->response);

  if ($tmhOAuth->response['code'] == 200) {
    $data = json_decode($tmhOAuth->response['response'], true);
    $name = array();
    foreach ($data as $val)
        {
            $name = $data[0]['screen_name'];
        }
        echo "this is the screen name  " .$name. "\n";
        $users += $data;
  } else {
    echo $tmhOAuth->response['response'];
    break;
  }
```

The rest of the code is the your original code.
$ids = 626 (following 626 people) 
$paging = 7 
pagesize = 100

When I run the php in a web browser, I am only able to extract 7 of the most recent followers (ie following user #626,following user 526,following user 426...) It seem to be echoing the last user on each page request.   When I adjust the $paging with different variables such as the number 626 I get {"errors":[{"code":17,"message":"No user matches for specified terms"}]} 

Unfortunately, I suspect this is fairly simple php looping problem, my strengths lie in options & MySQL.

Thank you in advance...

**Comment by ankitagarwal** [comment]
@optionsninja
Tried echoing $set and confirming it has the correct set of ids?

**Comment by optionsninja** [comment]
@ankitagarwal

Thanks, I tried that. and I got seven different arrays, with all the ID numbers. So I think it worked correctly? But didn't solve the problem... 
For example 

```
array(100) {
  [0]=>
  int(281089295)
  [1]=>
  int(342520620)
  [2]=>
  int(14297636)
  [3]=>
  int(21428988)
  [4]=>
  int(28818766)
  [5]=>
  int(18088644)
  [6]=>
  int(22079148)
  [7]=>
  int(40523026)
  [8]=>
  int(45417917)
 .... // all the way to 100 
}

```

What variable did you unset?

**Comment by themattharris** [comment]
In your code the foreach loop is badly formed. You have:

```
    foreach ($data as $val)
    {
        $name = $data[0]['screen_name'];
    }
    echo "this is the screen name  " .$name. "\n";
    $users += $data;
```

Which basically says, foreach value in the data array, give me the screen name of the first item and set it to $name. Once finished with the foreach loop, echo that name and add all of the responses I have to the $users variable.

What I think you want to do is this:

```
    foreach ($data as $val)
    {
        $name = $val['screen_name'];
        echo "this is the screen name  " .$name. "\n";
        $users[] = $name;
    }
```

**Comment by optionsninja** [comment]
Well that was easy! 

That worked perfectly, Thanks.
