### ISSUE TITLE
Composer is badly supported

### ISSUE THREAD

**Issue by philsturgeon** [themattharris/tmhOAuth#110]
Currently you have not set up the post-hook to notify packagist about your tags, which means that packagist only recognizes "dev-master". If you could push a 1.0 tomorrow it would breaks my live website, and at the moment I'm having to reference a specific commit instead.

Can you tag your versions ASAP please?

**Comment by philsturgeon** [comment]
Weird, in the installed copy of this lib I'm seeing a src folder, but in the master here it's missing the src folder.

http://d.pr/i/hrZW

**Comment by themattharris** [comment]
the version on packagist was created by a fork of this code. i'm working with kud (the creator of that fork) to fix the packagist version

**Comment by themattharris** [comment]
also, for info, all versions of tmhOAuth are tagged. e.g. https://github.com/themattharris/tmhOAuth/tree/0.7.3.

i'm happy to correct any issues or add things to composer to fix this

**Comment by philsturgeon** [comment]
I spotted the tags afterwards and sneakily updated my messages so only you would know that I originally complained a bit harder than it looks right now.

Sorry!

To get packagist up to date make sure you click Force Update, it'll run off and grab information on all the tags in the repo. Then try and follow the guide to get tags automatically hooked up.

http://d.pr/i/KHkk

If there are two repos, can you merge them to avoid confusion? It's madness right now :)

**Comment by themattharris** [comment]
np, yeah it'll get centralised on my copy of the repo - as i'm the one who develops and maintains it.
i became aware of this by another thread too - so this is all reactive.

i'm also aware composer has a broken psr-0 entry. as i've been through this with a number of different suggested forks i want to confirm my thinking is correct. so, the plan is to set autoload to this:

```
    "autoload": {
        "psr-0": { "tmhOAuth": "" }
    }
```

**Comment by themattharris** [comment]
fixed composer, updated https://packagist.org/packages/themattharris/tmhoauth and confirmed everything is working with a fresh project.
