### ISSUE TITLE
can not update via composer

### ISSUE THREAD

**Issue by gerkirill** [themattharris/tmhOAuth#113]
I have problem updating your library over composer. composer.phar update asks me for auth. credentials for github, which is strange, as it's a public repository. I guess the problem is you have "name": "themattharris/tmhoauth" in your composer.json, while the package is actually themattharris/tmhOAuth (letter case is the difference).
Try to do the following and you'll see what I mean:
git clone https://github.com/themattharris/tmhoauth.git

**Comment by AlexisSerneels** [comment]
Same bug here.

**Comment by themattharris** [comment]
thanks i'm looking into this.

**Comment by themattharris** [comment]
i've made some changes to the packagist meta information. please let me know if it works for you now.

**Comment by themattharris** [comment]
getting reports this is now fixed so i'm going to close this out. reopen if you are still having problems.
