### ISSUE TITLE
Sign In With Twitter Setting in my app settings page

### ISSUE THREAD

**Issue by oosswwaalldd** [themattharris/tmhOAuth#117]
Hi guys, 

In my app settings page there is a new thing "Sign in with Twitter" and is set to "No", my app is working well right now, I am using authorize link in the code, my question is:

What is does "Sign in with Twitter" setting do? should I set it to "Yes"?

I will appreciate your help in this mattter

**Comment by themattharris** [comment]
Sign in with Twitter is explained here: https://dev.twitter.com/docs/auth/sign-twitter
the setting on dev.twitter.com is used to indicate with the application supports the use of https://api.twitter.com/oauth/authenticate or not. (normal OAuth flow uses https://api.twitter.com/oauth/authorize)

i leave it off on my apps.
