### ISSUE TITLE
Why am I getting this result everytime after several hours of Streaming

### ISSUE THREAD

**Issue by ghost** [themattharris/tmhOAuth#120]
Hi,

I always see this results after 12 or more hours of running Streaming.php. Everything is working very well and you can see that I could capture around 500K while I was running the script in Amazon EC2 and storing it into MongoDB. I couldn't figure it out what happens every time that it shows me this and stops streaming: (I removed keys information)

tmhOAuth Object
(
    [response] => Array
        (
            [raw] => HTTP/1.1 200 OK
Content-Type: application/json
Transfer-Encoding: chunked
Content-Encoding: gzip

1
            [content-length] => 0
            [headers] => Array
                (
                    [HTTP/1.1 200 OK] => 
                    [Content-Type] => application/json
                    [Transfer-Encoding] => chunked
                    [Content-Encoding] => gzip
                    [] => 
                )

```
        [code] => 200
        [response] => 1
        [info] => Array
            (
                [url] => https://stream.twitter.com/1/statuses/filter.json
                [content_type] => application/json
                [http_code] => 200
                [header_size] => 103
                [request_size] => 650
                [filetime] => -1
                [ssl_verify_result] => 0
                [redirect_count] => 0
                [total_time] => 56821.328653
                [namelookup_time] => 0.010232
                [connect_time] => 0.21239
                [pretransfer_time] => 0.642929
                [size_upload] => 82
                [size_download] => 388024464
                [speed_download] => 6828
                [speed_upload] => 0
                [download_content_length] => -1
                [upload_content_length] => 82
                [starttransfer_time] => 0.871904
                [redirect_time] => 0
                [certinfo] => Array
                    (
                    )

                [redirect_url] => 
                [request_header] => POST /1/statuses/filter.json HTTP/1.1
```

User-Agent: tmhOAuth 0.7.5+SSL - //github.com/themattharris/tmhOAuth
Host: stream.twitter.com
Accept: _/_
Accept-Encoding: deflate, gzip
Authorization: OAuth oauth_consumer_key="********_", oauth_nonce="**_*****_", oauth_signature="**_*****_", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1363701664", oauth_token="**_******", oauth_version="1.0"
Content-Length: 82
Content-Type: application/x-www-form-urlencoded

```
            )

        [error] => 
        [errno] => 0
    )

[params] => Array
    (
    )

[headers] => Array
    (
        [Authorization] => OAuth oauth_consumer_key="*********", oauth_nonce="*********", oauth_signature="*********", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1363701664", oauth_token="*********", oauth_version="1.0"
    )

[auto_fixed_time] => 
[buffer] => 
[config] => Array
    (
        [user_agent] => tmhOAuth 0.7.5+SSL - //github.com/themattharris/tmhOAuth
        [timezone] => UTC
        [use_ssl] => 1
        [host] => api.twitter.com
        [consumer_key] => *********
        [consumer_secret] => *********
        [user_token] => *********
        [user_secret] => *********
        [force_nonce] => 
        [nonce] => *********
        [force_timestamp] => 
        [timestamp] => 1363701664
        [oauth_version] => 1.0
        [oauth_signature_method] => HMAC-SHA1
        [curl_connecttimeout] => 30
        [curl_timeout] => 10
        [curl_ssl_verifyhost] => 2
        [curl_ssl_verifypeer] => 1
        [curl_cainfo] => /var/tmp/tmhOAuth/tmhOAuth/cacert.pem
        [curl_capath] => /var/tmp/tmhOAuth/tmhOAuth
        [curl_followlocation] => 
        [curl_proxy] => 
        [curl_proxyuserpwd] => 
        [curl_encoding] => 
        [is_streaming] => 1
        [streaming_eol] => 

        [streaming_metrics_interval] => 60
        [as_header] => 1
        [debug] => 
        [streaming_callback] => my_streaming_callback
        [multipart] => 
    )

[metrics] => Array
    (
        [start] => 1363701663
        [interval_start] => 1363758484
        [tweets] => 541115
        [last_tweets] => 541114
        [bytes] => 2016371248
        [last_bytes] => 2016371132
        [tps] => 0.8
        [bps] => 2790.9
    )

[custom_headers] => Array
    (
    )

[method] => POST
[url] => https://stream.twitter.com/1/statuses/filter.json
[signing_params] => oauth_consumer_key=*********&oauth_nonce=*********&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1363701664&oauth_token=*********&oauth_version=1.0&track=%23BeliebersPutas%2C%23GrandTheftAutoMemories%2C%23ThereIsADifferenceBetween
[auth_params] => Array
    (
        [oauth_consumer_key] => *********
        [oauth_nonce] => *********
        [oauth_signature] => *********%3D
        [oauth_signature_method] => HMAC-SHA1
        [oauth_timestamp] => 1363701664
        [oauth_token] => *********
        [oauth_version] => 1.0
    )

[request_params] => track=%23BeliebersPutas%2C%23GrandTheftAutoMemories%2C%23ThereIsADifferenceBetween
[base_string] => POST&https%3A%2F%2Fstream.twitter.com%2F1%2Fstatuses%2Ffilter.json&oauth_consumer_key%*********%26oauth_nonce%*********%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1363701664%26oauth_token%*********%26oauth_version%3D1.0%26track%3D%2523BeliebersPutas%252C%2523GrandTheftAutoMemories%252C%2523ThereIsADifferenceBetween
[signing_key] => *********
[auth_header] => OAuth oauth_consumer_key="*********", oauth_nonce="*********", oauth_signature="*********", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1363701664", oauth_token="*********", oauth_version="1.0"
```

)

Note: All I want is to run this script (streaming.php) none stop and it keeps looking for tracks as long as I stop the script not stopping by itself. Should I do something to prevent this?

Thank you so much, I enjoy the library so much :)

**Comment by ghost** [comment]
OK more follow on this issue (which I think it is better on the example side since i used example but i thought maybe it is related to the config not the code itself. I don't know your choice).

I wrote a script that check whether the code is running as a process or not. if it's not it runs it. (I check every minute by cron job). So far I have seen anything on my log file and also it's been running for days and collected 12million tweets as a sample. So there is nothing wrong from the API authentication as well to block script.

So if I can get a straight answer that the config array was the right to use as streaming API you can close this.

Thanks a lot :)

**Comment by destronije** [comment]
Hi, i am facing the exact same issue with streaming api, did u make any progress on this issue?

Thanks in advance. :)

**Comment by themattharris** [comment]
by design Twitter's streaming API can roll their servers or occasionally disconnect you - so it's important your process that's running this code is written to reconnect on disconnect -- but also to back off on error (just in case).

also, if you are running this in a production style environment (rather than development) i recommend you have it started by a background crontab or similar. that way it's not running under an interactive session that could be terminated due to inactivity.

**Comment by ghost** [comment]
Yes that's what I thought so I run it in the background and check the process every minute to see whether it's working or not to run it again. So in the worse case scenario I will lost a minute data.
Thank you very much, the reason I asked was to see that if the problem is from my configurations and clearly it's something from Twitter. 
I managed to collect 52million tweets in three weeks for testing and stressing server on EC2 and that worked very well for me.

Thanks Matt for the library and the support :)
