### ISSUE TITLE
Class 'tmhUtilities' not found (with Composer)

### ISSUE THREAD

**Issue by SteveEdson** [themattharris/tmhOAuth#121]
We're using tmhOAuth with composer, when trying to execute the line

```
echo tmhUtilities::pr($tmhOAuth->response['response']);
```

We get the error `PHP Fatal error:  Class 'tmhUtilities' not found`. Should this be autoloaded? How can we initialise the class? The examples are 7 months old and do not provide any examples of use with composer.

Thanks.

**Comment by oosswwaalldd** [comment]
Are you sure you did include the php lib file at the top of your script?

**Comment by SteveEdson** [comment]
Included the `vendor/autoload.php` file yeah. The tmhoauth class works OK, its just the utilities. The tmhoauth autoload is defined in the `composer.json`, but the utilities class isn't. Think that might be the issue?

**Comment by themattharris** [comment]
this file was removed on 0.8.0 as it isn't part of the core lib. if you found it useful please open a new issue to put tmhUtilities into it's own project.
