### ISSUE TITLE
URL of the request

### ISSUE THREAD

**Issue by trante** [themattharris/tmhOAuth#122]
I need support for some issue. I have such request and I need to get URL of this request. How can I get URL?
Thank you.

```
   $params = array(
        'q'        => "keyword,
        'rpp'      => '1000',
        'page'    => '1'
    );
   $tmhOAuth->request( 'GET', 'http://search.twitter.com/search.json', $params, false );
```

**Comment by curt2008** [comment]
The URL you're attempting to get would be

http://search.twitter.com/search.json?q=keyword&rpp=1000&page=1

Just remember for the "q" variable it must be URL encoded

**Comment by themattharris** [comment]
this is an older ticket reference the now deprecated search api.
but, either way, under tmhOAuth 0.8 onwards the final requested URL can be extracted from the tmhOAuth library by asking for $tmhOAuth->request_settings['url'];
