### ISSUE TITLE
$_SESSION Not working with POST statuses/update_with_media

### ISSUE THREAD

**Issue by LeagueRivals** [themattharris/tmhOAuth#126]
Hi Matt, I've been using Oauth_Flow to gain access to user_token and user_secret on my site so visitors can then POST statuses/update_with_media. It was working fine yesterday however it's stopped today. I updated your code for posting statuses/update_with_media below but all I get is {"errors":[{"message":"Bad Authentication data","code":215}]}

<code>
<? 
session_start();
require '.../tmhOAuth.php';
require '.../tmhUtilities.php';
$tmhOAuth = new tmhOAuth(array(
  'consumer_key'    => 'xxxxx',
  'consumer_secret' => 'xxxxx',
  $_SESSION['user_token'],
  $_SESSION['user_secret'],
  ));
  $params = array(
    'image' => "@{$_FILES['image']['tmp_name']};type={$_FILES['image']['type']};filename={$_FILES['image']['name']}",
  );
$code = $tmhOAuth->request(
  'POST',
  'https://api.twitter.com/1.1/statuses/update_with_media.json',
  array(
    'media[]'  => "@{$image};type=image/jpeg;filename={$image}",
    'status'   => " " . $status
  ),
  true, // use auth
  true  // multipart
);
if ($code == 200) {
  tmhUtilities::pr(json_decode($tmhOAuth->response['response']));
} else {
  tmhUtilities::pr($tmhOAuth->response['response']);
}
?>
</code>

I also updated the oauth_flow url for 1.1 as so:

<code>
  $code = $tmhOAuth->request(
    'GET',
    $tmhOAuth->url('1.1/account/verify_credentials.json')
  );
</code>

There is a link on the index page (where the visitor signs in) that takes them to the page with the statuses/update_with_media code above. I'm stumped on how to fix it? I tried using $consumer_key & $consumer_secret in the code above as well with no luck.

Any help would be greatly appreciated.

**Comment by themattharris** [comment]
bad authentication data means either the consumer key, consumer secret, oauth token or oauth secret are wrong or missing. the first thing to do in these situations is check your consumer key and secret are valid. then check you are configuring tmhOAuth correctly. in your example code you have this:

```
$tmhOAuth = new tmhOAuth(array(
'consumer_key' => 'xxxxx',
'consumer_secret' => 'xxxxx',
$_SESSION['user_token'],
$_SESSION['user_secret'],
));
```

when instead you should have this:

```
$tmhOAuth = new tmhOAuth(array(
'consumer_key' => 'xxxxx',
'consumer_secret' => 'xxxxx',
'token' => $_SESSION['user_token'],
'secret' => $_SESSION['user_secret'],
));
```

(notice the user_token and user_secret now have array key names as opposed to just being values in the array).

if, after fixing that, you still get an error; inspect the contents of the $_SESSION object and check the token and secret are being stored under the values $_SESSION['user_token'] and $_SESSION['user_secret'].
