### ISSUE TITLE
Add multiple locations to filter tweets

### ISSUE THREAD

**Issue by darkwish121** [themattharris/tmhOAuth#127]
Here is my code it works with single location but when I add multiple locations it doesn't work for me. When I pass array it give me error

Notice: Array to string conversion in D:\wamp\www\twitter\tmh\tmhOAuth.php on line 629

"Location track items must be given as pairs of comma separated lat/longs"

Question 1: How can I get tweets from multiple locations?
Question 2: what return callback function's parameters $length and $metrics?

<?php
set_time_limit(0);
require_once(dirname(dirname(dirname(**FILE**))).'/config.php');

function my_streaming_callback($data, $length, $metrics) {
    var_dump($data);
    //exit;
}

require '../tmhOAuth.php';
require '../tmhUtilities.php';
$tmhOAuth = new tmhOAuth(array(
  'consumer_key'    => '***_', 
  'consumer_secret' => '**__',
  'user_token'      => '_**_',
  'user_secret'     => '**_*',
));

$method = 'https://stream.twitter.com/1.1/statuses/filter.json';

$params = array(
  // matches tweets containing 'twitter' 'Twitter' '#Twitter'
  //'track'     => 'twitter',  
  // matches tweets containing 'twitter' or 'love' (no spaces!)
  //'track'   => 'twitter,love'
  // matches tweets containing 'twitter' and 'love'
  //'track'   =>'twitter love'
  // Warning on extra spaces - below matches 'twitter' but not 'love'!
  //'track'   =>'twitter, love'
  // Around Twitter HQ. First param is the SW corner of the bounding box
  'locations' => '-74, 40, -73, 41'

```
 //'locations' =>  array(-122.75, 36.8, -121.75, 37.8),
 //'locations' =>  array(-74, 40, -73, 41)  
```

  //'follow'    => '777925' // themattharris
);

$tmhOAuth->streaming_request('POST', $method, $params, 'my_streaming_callback');

// output any response we get back AFTER the Stream has stopped -- or it errors
tmhUtilities::pr($tmhOAuth);

**Comment by themattharris** [comment]
in tmhOAuth 0.8 onwards the way to call the function with arguments like this is to do this:

```
$code = $tmhOAuth->streaming_request(
  'POST',
  'https://stream.twitter.com/1.1/statuses/filter.json',
  array(
    'locations' => '-74, 40, -73, 41',
  ),
  'my_streaming_callback'
);
```

to look up multiple locations you keep appending the box-coordinates to the locations string, comma separated from the previous set.

for example, to get Tweets geo-tagged within San Francisco OR New York City you would do:

```
$code = $tmhOAuth->streaming_request(
  'POST',
  'https://stream.twitter.com/1.1/statuses/filter.json',
  array(
    'locations' => '-122.75,36.8,-121.75,37.8,-74,40,-73,41',
  ),
  'my_streaming_callback'
);
```

there's more information on the location parameter on the Twitter developer site here: https://dev.twitter.com/docs/streaming-apis/parameters#locations

to answer question 2:
the $length and $metrics params are part of the streaming callback function called from the curlWrite method handler in tmhOAuth. specifically:

$length is the string length of the $content just passed to you. it's more a helper than anything else. in my curlWrite method handler i look after the byte length reporting that's needed to keep curlWrite functioning.

$metrics is an array containing information about the streaming connection you have open. it contains things like the messages received over the streaming api, the bytes sent, the messages per second and bytes per second rate.

hope that helps.
