### ISSUE TITLE
Guidance for storing credentials in a database

### ISSUE THREAD

**Issue by jamesinealing** [themattharris/tmhOAuth#128]
Hi, I am new to tmhOAuth but have just successfully installed and configured it and am starting to have a play around. I am also using the 140dev framework.

I've seen lots of mentions of permanently storing credentials in a secure database but wondered if anyone had any guidance and/or code snippets that outline the best way to accomplish this? Thanks

**Comment by themattharris** [comment]
hey @jamesinealing,
each person has their own preferred way of doing this, based on the systems and other libraries they may be using. as such these sort of questions are better suited to the Twitter Developer forums (dev.twitter.com/discuss) where you can gather many different approaches before making your final decision.
