### ISSUE TITLE
Twitter API V1 Retirement 

### ISSUE THREAD

**Issue by wiresfj** [themattharris/tmhOAuth#132]
Hi,

been using the tmhOAuth twitter interface and its great (Thank you)

I've had a look and I can't see any postings about the fact Twitter are changing the API and V1 will stop working in June 2013.

I might being stupid or missing something but will Matts great code work with the new V1.1 twitter API?

Sorry if I'm being stupid.

Many thanks,
Patrick

**Comment by adamcbrewer** [comment]
I've been using v1.1 with no issues so far. I've only used the `request` method though, no streaming.

**Comment by willpower232** [comment]
I believe this is just an OAuth class so should work with any version of the twitter API.

**Comment by wiresfj** [comment]
Hi guys,

well as I expected my website has stopped working now. The twitter routines which all used V1.0 have given up.

Its probably really easy, but how do I make them work with V1.1?

It took me long enough to get them working the way I wanted as it is, So I don't really want to start hacking around Matts fine code and really messing things up.

Any help would be great because as it is right now my site is down...

Many thanks,
Patrick

**Comment by adamcbrewer** [comment]
@wiresfj are you talking specifically about the Twitter v1.0 API? It seems like they [announced its retirement yesterday](https://dev.twitter.com/blog/api-v1-is-retired).

Switching to v1.1 it's that much different, but if you wanted something to test/work with quickly then you're welcome to [use a class I wrote based on the v1.1 API](https://github.com/adamcbrewer/tmhOAuth/blob/master/twitterApi.php), using this OAuth library.

I hope that helps?

**Comment by wiresfj** [comment]
Hi Adam,

yes I've been using the Twitter v1.0 API.

I knew it was being retired yesterday, so had been looking around for a solution.

I'm not sure how to switch to V1.1
I've had a look at your code and from what I can see its the URL thats changed.
i.e. url('1.1/statuses/update')

I'm using Twitter pic, updating status and direct messages.

Thank you for sharing your nice work but it doesn't cover the sections I'm trying to use.

I'm hoping that to make v1.1 work it is just a case of changing the URL in Matts code, but I really don't want to make matters worse. There seems to be URL references in many places.

I can't be the only person that has hit this problem.

Thanks again Adam, I really appreciate your feedback. As I said my site is now down so its causing me a slight problem.

**Comment by adamcbrewer** [comment]
@wiresfj I can't say it's as easy as swapping out the URL (v1.1 as apposed to v1.0), but you'd be better off [checking the documentation](https://dev.twitter.com/docs/api/1.1) to cater for anything specific.

**Comment by wiresfj** [comment]
Cheers Adam,

I was hoping it was going to be a simple job.

I've had a look at all your suggestions and at the moment its beyond my programming ability (I'm more an embedded software engineer).

Not sure what to do really, I can't be the only person who is using Matts code to post tweats and direct messages.

I don't know if I'm missing something and Matts code works fine with API V1.1 and its my implementation of it which is really just based on the examples given. 

I'm a great believer of the self help, but I'm just totally stuck on this one.

Thank you for your time in pointing me in various directions, I don't want to keep hassling you. I might try contacting Matt as a last resort.

Thanks again.

Patrick

**Comment by adamcbrewer** [comment]
Sorry I can't be of more help, but it really depends what your code looks like and how you're trying to implement it as to what you need to change.

**Comment by wiresfj** [comment]
Hi Adam / everyone.

OK I've solved the problem. It was very easy in the end.

To help anyone else having the same issue, here is what I did.

I am using Matts latest files. I've not changed anything.

I've created these two PHP functions below.

One post a status tweet and the other does a direct message.

They are both working with the new Twitter api 1.1 requirements.

All I had to do in the end was this,

Change the URL from 1/statuses/update
to
1.1/statuses/update

$tmhOAuth->url('1.1/statuses/update'),

Anyway here they are, hope it helps someone else.

Just as a note, when I was debugging my code I added the printf / echo just as a quick test.
They are commented out for real life applications.

I'm sure everyone will follow it.

Many thanks (especially to Adam) 

All the best for now.
Patrick

// ****************************************************\* //
// **\* This function will post a Tweet Status Update **\* //
// ****************************************************\* //
function Tweet_Status($tweetMessage)
{
  $tmhOAuth = new tmhOAuth(array(
              'consumer_key'    => Twitter_Consumer_Key,
              'consumer_secret' => Twitter_Consumer_Secret,
              'user_token'      => Twitter_User_Token,
              'user_secret'     => Twitter_User_Secret,
              ));

  // Check for 140 characters
  if(strlen($tweetMessage) <= 140){
      // Status Update Tweet
      $code = $tmhOAuth->request('POST',
      $tmhOAuth->url('1.1/statuses/update'),
      array('status' => $tweetMessage));

```
/*
  printf("Code = %u",$code);
  // 200 = all good
  if ($code == 200) echo " All OK....";
  else echo " Opps Error";   
  */
  }
```

}

// *****************************************************\* //
// **\* This function will post a Direct Message Tweet **\* //
// *****************************************************\* //  
function Tweet_Direct_Message($tweetName, $tweetMessage)
{
 $tmhOAuth = new tmhOAuth(array(
             'consumer_key'    => Twitter_Consumer_Key,
             'consumer_secret' => Twitter_Consumer_Secret,
             'user_token'      => Twitter_User_Token,
             'user_secret'     => Twitter_User_Secret,
             ));

  // Check for 140 characters
  if(strlen($tweetMessage) <= 140){
    // Direct Message Tweet
    $code = $tmhOAuth->request('POST',
    $tmhOAuth->url('1.1/direct_messages/new'),
    array('text' => $tweetMessage,
    'screen_name' => $tweetName
    )); 

 /*
    printf("Code = %u",$code);
    // 200 = all good
    if ($code == 200) echo " All OK....";
    else echo " Opps Error"; */  
    }
}

**Comment by pvledoux** [comment]
@wiresfj Thanks for your indication, I could repair our applications by just replace $tmhOAuth->url('1/statuses/update') by $tmhOAuth->url('1.1/statuses/update')

**Comment by themattharris** [comment]
thanks to everyone who commented and helped out here.

as i just commented in issue #137, and as a few have mentioned here -- Twitter turned off their v1 API the other day. this change doesn't affect tmhOAuth directly, but it will mean any scripts you have need to be updated to use URLs under /1.1/ instead of /1/. you can find more information about the new API at https://dev.twitter.com/docs/api/1.1

i'm also push up a new repository at https://github.com/themattharris/tmhOAuthExamples for version 0.8 of tmhOAuth (being pushed in the next hour or so)

**Comment by fchristant** [comment]
@wiresfj Thanks man, you're a life saver. Your fix worked perfectly for me.
