### ISSUE TITLE
Library stopped working May 30?

### ISSUE THREAD

**Issue by gswalden** [themattharris/tmhOAuth#133]
On May 30th, my website utilizing this library became unable to communicate with the Twitter API. I have checked on both my live and dev servers, with the same results. I have since set-up a completely separate environment, and pulled the latest versions of cacert.pem, composer.json, tmhOAuth.php, & tmhUtilities.php from the main TMHOAuth repo, and friends.php from the Examples repo. I updated friends.php to use the 1.1 API and added my tokens, but no other changes were made, and only these five files were in the directory. Still, unable to communicate with Twitter. I tried an entirely new Twitter application (new tokens), same result.

Anyone else having problems, or know of a solution?

**Comment by themattharris** [comment]
what is the output of the script. the $tmhOAuth->response['error'] should contain a string of some kind explaining why a connection could not be established.

**Comment by gswalden** [comment]
It reads (from my live site): Failed to connect to 199.59.149.232: Network is unreachable
During my lunch break I'll try from my local dev server.

**Comment by themattharris** [comment]
from the live server can you ping api.twitter.com? what about traceroute? if those dont succeed you most likely have a network or routing issue. to fix that you'll need to talk to your hosting provider/network engineering team

**Comment by gswalden** [comment]
You're correct, my dev server in Cleveland is having no problems while the live server in NC is. Thanks for you help Matt!
