### ISSUE TITLE
Class error when attempting to send tweet.

### ISSUE THREAD

**Issue by purplelounge** [themattharris/tmhOAuth#136]
I have followed a blog post guide which advises using your package to send tweets via my script. When running the script it has a series of echo commands for debugging but they no longer show. Instead it loads up your github page displaying the contents of tmhOAuth.php and tmhUtilities.php with the error 

Fatal error: Class 'tmhOAuth' not found in /home/cliftont/public_html/discount.php on line 6

at the end. The line in question is:

$tmhOAuth = new tmhOAuth(array(
  'consumer_key' => 'etc etc etc',
  'consumer_secret' => 'etc etc etc',
  'user_token' => 'etc etc etc',
  'user_secret' => 'etc etc etc',
));

I am using PHP 5.3.18, I'm not sure what else to say really.

**Comment by willpower232** [comment]
You did download a copy of the classes and include() or require() 'ed them in your file?

**Comment by willpower232** [comment]
Okay try using the require function so that it throws an error if it cannot find the file. Presuming those two files are located outside your public_html directory, have you made sure the permissions on those files are correct?

**Comment by willpower232** [comment]
Ah yes, my bad. Are you sure the files you have contain only php and nothing else?

**Comment by willpower232** [comment]
Not my repository, just offering an attempt at a helping hand :-P can never be sure from here of what you have

**Comment by willpower232** [comment]
The files you have on your server/computer, if you open them, do they start with <?php ?

**Comment by purplelounge** [comment]
On 06/06/13 22:34, Will Power wrote:

> The files you have on your server/computer, if you open them, do they 
> start with <?php ?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/themattharris/tmhOAuth/issues/136#issuecomment-19075733.
> 
> Yes the script starts with <?php

Your name is familiar by the way, are you in the South East UK by any 
chance?

**Comment by sabl0r** [comment]
Did you download the files in raw format?
Example: https://raw.github.com/themattharris/tmhOAuth/master/tmhOAuth.php

**Comment by willpower232** [comment]
Formerly, although the midlands is now my home. Curious indeed. The raw output was going to be my next guess...

**Comment by willpower232** [comment]
Alas I cannot say I had such an extravagant birthday :-P

**Comment by willpower232** [comment]
Ah...I mean that I did not have a DJ at my 18th birthday or any birthday for that matter...

**Comment by sabl0r** [comment]
Please close the issue if it's working for you now.
