### ISSUE TITLE
twitter 1.0 is gone, all code is broken

### ISSUE THREAD

**Issue by hashtagsports** [themattharris/tmhOAuth#137]
anyone have any ideas on how to get my apps back up and running for twitter 1.1, i'm using search

**Comment by kroguz** [comment]
same here

**Comment by wiresfj** [comment]
Hi I was having the same problem yesterday, all my code went down.

In the end it was very simple to fix. All I had to do was change the URL.

Here is a copy of the post I did explaining what I did.

It might help if you post a snippet of your code on here that's not working.

I've not used the search, but I suspect the change will be very similar.

Anyway here is my post from yesterday, hope it helps.

Hi Adam / everyone.

OK I've solved the problem. It was very easy in the end.

To help anyone else having the same issue, here is what I did.

I am using Matts latest files. I've not changed anything.

I've created these two PHP functions below.

One post a status tweet and the other does a direct message.

They are both working with the new Twitter api 1.1 requirements.

All I had to do in the end was this,

Change the URL from
1/statuses/update
to
1.1/statuses/update

$tmhOAuth->url('1.1/statuses/update'),

Anyway here they are, hope it helps someone else.

Just as a note, when I was debugging my code I added the printf / echo just as a quick test.
They are commented out for real life applications.

I'm sure everyone will follow it.

Many thanks (especially to Adam)

All the best for now.
Patrick

// ****************************************************\* //
// **\* This function will post a Tweet Status Update **\* //
// ****************************************************\* //
function Tweet_Status($tweetMessage)
{
$tmhOAuth = new tmhOAuth(array(
'consumer_key' => Twitter_Consumer_Key,
'consumer_secret' => Twitter_Consumer_Secret,
'user_token' => Twitter_User_Token,
'user_secret' => Twitter_User_Secret,
));

// Check for 140 characters
if(strlen($tweetMessage) <= 140){
// Status Update Tweet
$code = $tmhOAuth->request('POST',
$tmhOAuth->url('1.1/statuses/update'),
array('status' => $tweetMessage));

/*
  printf("Code = %u",$code);
  // 200 = all good
  if ($code == 200) echo " All OK....";
  else echo " Opps Error";  
  */
  }
}

// *****************************************************\* //
// **\* This function will post a Direct Message Tweet **\* //
// *****************************************************\* //

function Tweet_Direct_Message($tweetName, $tweetMessage)
{
$tmhOAuth = new tmhOAuth(array(
'consumer_key' => Twitter_Consumer_Key,
'consumer_secret' => Twitter_Consumer_Secret,
'user_token' => Twitter_User_Token,
'user_secret' => Twitter_User_Secret,
));

// Check for 140 characters
if(strlen($tweetMessage) <= 140){
// Direct Message Tweet
$code = $tmhOAuth->request('POST',
$tmhOAuth->url('1.1/direct_messages/new'),
array('text' => $tweetMessage,
'screen_name' => $tweetName
));

/*
printf("Code = %u",$code);
// 200 = all good
if ($code == 200) echo " All OK....";
else echo " Opps Error"; */

}
}

**Comment by wiresfj** [comment]
PS This helped me a lot. (Thanks to Adam)

https://dev.twitter.com/docs/api/1.1

**Comment by uavster** [comment]
Thank you, wiresfj. It really helped me fix the problem. My request url was "1/statuses/user_timeline" and I changed it for "1.1/statuses/user_timeline". Everything works like a charm now.

**Comment by themattharris** [comment]
thanks to everyone who commented. as a few have mentioned Twitter turned off their v1 API the other day. this change doesn't affect tmhOAuth directly, but it will mean any scripts you have need to be updated to use URLs under /1.1/ instead of /1/. you can find more information about the new API at https://dev.twitter.com/docs/api/1.1

i'm also push up a new repository at https://github.com/themattharris/tmhOAuthExamples for version 0.8 of tmhOAuth (being pushed in the next hour or so)
