### ISSUE TITLE
Still can't use 1.1 twitter API

### ISSUE THREAD

**Issue by ErikSMA** [themattharris/tmhOAuth#138]
Hello,

I followed on other topics about how to make my code work again after depreciation of the old Twitter API.

Unfortunately it still doesn't work for me... I replaced the tmhOAuth.php file I had (a really old 2010 one) by the brand new one uploaded yesterday and as other users mentioned, added "/1.1/statuses/update" where needed. 

The only strange thing is that I didn't have " /1/statuses/update " but only " /statuses/update "

And after some dozens of tries, I have to admit that it doesn't work yet... 

Here is the request to tmhOAuth.php I'm using : 

function sendtweet($message) {
    require 'tmhOAuth.php';
    $tmhOAuth = new tmhOAuth(array(
        'consumer_key' => 'XXX',
        'consumer_secret' => 'XXX',
        'user_token' => 'XXX',
        'user_secret' => XXX',
    ));

```
$tmhOAuth->request('POST', $tmhOAuth->url('/statuses/update'), array(
    'status' => utf8_encode($message)
));
```

}

Can anyone tell me what's wrong with my code ?

Thanks a lot !
Have a nice day

**Comment by iabhinavgupta** [comment]
Hi ErikSMA,

Try to change value of oauth_version to "1.1" in tmhOAuth.php..Hope it will works then.

**Comment by Wraithers** [comment]
Hi ErikSMA,

Two things:

1) Change <i>'user_token'</i> to <i>'token'</i>
Change <i>'user_secret'</i> to <i>'secret'</i>

2) Make sure your <i>entire</i> Twitter application has an Access Level of 'Read and Write'
Check your apps' Details page. If you change your Access Level, then be sure to recreate your Access Token and refresh until it the Access Level is 'Read and Write' for that too

I've attached an image of my php script that works.
Check @aaron_khare on Twitter for the test message.
All the best! :+1:

![PHP Script Send Tweet](https://f.cloud.github.com/assets/4705057/658168/c97e4c76-d5c2-11e2-926f-47fcc24adae9.png)

**Comment by ErikSMA** [comment]
Hello ! 

Thanks for your help. I followed your advices but unfortunately it doesn't work yet. 

I changed the value of "oauth version" in tmhOAuth.php : 

// oauth signing variables that are not dynamic
        'oauth_version'              => '1.1',
        'oauth_signature_method'     => 'HMAC-SHA1',

![image](https://f.cloud.github.com/assets/4703199/658601/cf382cc0-d5f6-11e2-817b-5edf221b6756.png)

And Wraithers, I changed the token and secret following your file (thanks for sharing) and also checked what you told me in the Twitter application details. But everything was already fine. In the OAuth tool, I saw something that could be not right : 

![image](https://f.cloud.github.com/assets/4703199/658602/26e33316-d5f7-11e2-9f62-fa9bb6ae0ddb.png)

But it seems to be just values used to generate a code, not really something saved in the application settings ? 

I just don't really get what is wrong with this. Wraithers, what version of tmhOAuth are you using ? I'm using the very latest one, 0.8.2

Thanks a lot for helping ! 

Take care

Erik

**Comment by oosswwaalldd** [comment]
Hi, did you do all the procedure with the file cacert.pem explained in the Get Started section? I think that would help you

**Comment by ErikSMA** [comment]
Hi oosswwaalldd, 

Yes I just did. Your idea was good, as I had this error message : 

error code : error setting certificate verify locations: CAfile: E:\wamp\www\shootmeagain\cacert.pem CApath: E:\wamp\www\shootmeagain 0

But even after placing cacert.pem it doesn't tweet. I know get the error 400. Where can I find what is this error 400 ?

Just to be sure, I even copied the exact calling function used in the example : 

$code = $tmhOAuth->user_request(array(
  'method' => 'POST',
  'url' => $tmhOAuth->url('1.1/statuses/update'),
  'params' => array(
    'status' => utf8_encode($message) )

```
));
```

Thanks a lot

**Comment by alexander-irbis** [comment]
ErikSMA, just append ".json" to the url:

$code = $api->request('POST', $api->url('1.1/statuses/update.json'), ['status' => $status]);

At least this code works fine for me

**Comment by lbriceno92** [comment]
doesnt the method url(' ')  return the actual url with the .json appended?

**Comment by ErikSMA** [comment]
Yeah, I tried but it didn't change anything to my issue... 

The error 400 just seems to be a "Bad request" error... but how can I debug it ? I mean, how can I get a more detailed overview on the error than just this error 400 thing ? It could be anything...

**Comment by sothychan** [comment]
ErikSMA, worth a shot, you need to change oauth_version back to 1.0.  The Twitter API changed from 1.0 to 1.1, not oauth.  Once you change that back to 1.0, assuming you did everything else correct like putting cacert.pem in the same directory, it should work if you use 1.1/statuses/update.json as the URL.  At least it worked for me.  tmhOAuth worked right out of the box and no modifications were necessary.  Make sure you're losing the latest one 0.8.2.  Good luck.

**Comment by ErikSMA** [comment]
Yeah, it finally works ! THanks a lot for your help everyone, especially sothychan who gave the final push. I'm really happy that it works again.

Have a nice day everyone !

**Comment by sothychan** [comment]
ErikSMA,

Glad to hear it's working now!

Cheers,
Sothy

On 6/18/13 10:12 PM, ErikSMA wrote:

> Yeah, it finally works ! THanks a lot for your help everyone, 
> especially sothychan who gave the final push. I'm really happy that it 
> works again.
> 
> Have a nice day everyone !
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/themattharris/tmhOAuth/issues/138#issuecomment-19663431.

## 

Sothy Chan
Web Developer
www.crowdstir.com
Mobile: 805.350.8720

**Comment by themattharris** [comment]
thanks everyone for supporting each other in this. closing this out as @ErikSMA says it's working now.
