### ISSUE TITLE
Suggestion: Add options to trate IDs as String.

### ISSUE THREAD

**Issue by nadiamoe** [themattharris/tmhOAuth#14]
Hi there!

The high use of twitter have generated really HUGE IDs for everything: Statuses, Users, DMs...
When moving large amounts of data, storing that IDs as Integers requires A LOT of memory to be allocated, and also so much CPU usage. The apps could be too much smaller if you could add an option to return these IDs as Strings instead of Integers.
Just an idea, not sure if possible :S

Best regards, Roobre.

**Comment by themattharris** [comment]
The Twitter API responses include id_str in addition to id so this information is available to you.

If you prefer to use the String versions over the Integer versions you could do this:
$obj['id'] = $obj['id_str'];
unset($obj['id_str']);

Hope that helps.
