### ISSUE TITLE
Script broken since transition to Twitter v1.1

### ISSUE THREAD

**Issue by vikinggoat** [themattharris/tmhOAuth#142]
Script that was working before since the v1.1 transition isn't working anymore, I've made the 1 to 1.1 alteration, downloaded the latest tmhOauth release, changed any references of user_token and user_secret to token and secret, even made an alteration to tmhOauth.php (changed **_DIR**_ to dirname(**FILE**) on lines 67 and 68); but I'm still getting
Error: {"errors":[{"message":"Bad Authentication data","code":215}]}  from tmhOauth, just can't seem to find the issue at hand.

Any other suggestions?

**Comment by themattharris** [comment]
"Bad Authentication data" means one of these values isn't set or correct:

```
$tmhOAuth = new tmhOAuth(array(
        'consumer_key'    => 'YOUR_CONSUMER_KEY',
        'consumer_secret' => 'YOUR_CONSUMER_SECRET',
        'token'           => 'A_USER_TOKEN',
        'secret'          => 'A_USER_SECRET',
));
```

if those are set correctly, check the application record on dev.twitter.com to ensure the consumer key and secret, and your user token and secret, still match.

**Comment by themattharris** [comment]
i'm closing this one out as there hasn't been any new information to follow up on.
