### ISSUE TITLE
Requires PHP 5.3+ even though summary page says tmhOAuth supports PHP 5.1+

### ISSUE THREAD

**Issue by kashum** [themattharris/tmhOAuth#145]
The tmhOAuth->reconfigure() method is using __DIR__ which was only introduced in PHP 5.3, so you'll get a "Notice: Use of undefined constant __DIR__ - assumed '__DIR__'" notice when used with pre-5.3 versions of PHP.

Obviously you can put the following at the top of the class file to get it working in earlier PHP versions, but it should be fixed properly in the class.

define('__DIR__',dirname(__FILE__));

**Comment by ohrockyrocky** [comment]
Agree - this affects whether the cacert.pem can be found.

Very oddly the version of PHP used by my hosting company's CRON was pre-5.3 and so failed, whereas the command line used 5.3 and was working. Took me a while to sort...

**Comment by themattharris** [comment]
while i can add this, i do say in the readme that the library is only tested with PHP 5.3 -- and the composer.json file states 5.3 or higher is required.

can you link me to the summary page which states that tmhOAuth supports PHP 5.1+ so i can have it corrected.

**Comment by kashum** [comment]
Hey Matt. Sorry, I must have assumed it meant 5.1. Under dependencies in the README.md it says:

"The library has been tested with PHP 5.3+ and relies on CURL and hash_hmac. The vast majority of hosting providers include these libraries and run with PHP 5.1+."

I guess I thought this implied that while it was tested under 5.3, it should probably work under 5.1 because it often has those libraries included. Obviously the libraries aren't the issue here though, it's PHP 5.3 features that you're using.

I've got no problem whether it's designed to support 5.1 and 5.2 or not, but maybe tweak the above text to be clearer about what the intention is.

Personally I think not using __DIR__ is a pretty simple change, and instantly makes your library work in at least PHP 5.2 which is what we're running and is pretty common.

Don't get me wrong, love your work. :-)

**Comment by themattharris** [comment]
hey @kashum,
no problem, i appreciate the note about it being unclear. i'm restoring the dirname(**FILE**) code in 0.8.3.

**Comment by themattharris** [comment]
shipped in 0.8.3
