### ISSUE TITLE
I keep getting response code 401

### ISSUE THREAD

**Issue by Sebastien-T** [themattharris/tmhOAuth#146]
Hi all,
I've been trying to use this lib to automatically post tweets from my website. But each time I get the response code 401.

Does anyone know what this code means?
How can I debug this?

Here is my code:

include('twitter/tmhOAuth.php');

$tmhOAuth = new tmhOAuth(array(
  'consumer_key' => 'xxx',
  'consumer_secret' => 'xxx',
  'token' => 'xxx',
  'secret' => 'xxx',
));

$response = $tmhOAuth->request('POST', $tmhOAuth->url('1.1/statuses/update.json'), array(
  'status' => $status
));

**Comment by oosswwaalldd** [comment]
https://dev.twitter.com/docs/error-codes-responses

**Comment by Sebastien-T** [comment]
Oh boy, I feel so dumb right now!
Thanks a lot oosswwaalldd :) You pushed me in the right direction
