### ISSUE TITLE
Application-only authentication

### ISSUE THREAD

**Issue by quantizer** [themattharris/tmhOAuth#147]
Hello, I need more rate limits for Twitter API and twitter has better limits if app is pssed [application-only authentication](https://dev.twitter.com/docs/auth/application-only-auth) is tmhOAuth provides methods for this type of authorization or it could be a new feature :-)?

**Comment by themattharris** [comment]
tmhOAuth supports app only authentication. an example of how to use it is in the tmhOAuthExamples project here: https://github.com/themattharris/tmhOAuthExamples/blob/master/cli/search.php, which makes use of the bearer token set here: https://github.com/themattharris/tmhOAuthExamples/blob/master/tmhOAuthExample.php#L55

**Comment by quantizer** [comment]
Thanks. Sorry, I can't find it in docs.
