### ISSUE TITLE
Uploading files from memory

### ISSUE THREAD

**Issue by mmiliaus** [themattharris/tmhOAuth#15]
I am wondering if it is possible to upload file from the memory to twitter, instead of storing it first on a disk.
Thanks!

**Comment by ninjamonkno1** [comment]
If you are after sending the an upload direct without storing it on the server then look at the comments on line 37 https://github.com/themattharris/tmhOAuth/blob/master/examples/photo_tweet.php 

It says

// we're using a hardcoded image path here. You can easily replace this with
// an uploaded image - see images.php in the examples folder for how to do this
// 'image = "@{$_FILES['image']['tmp_name']};type={$_FILES['image']['type']};filename={$_FILES['image']['name']}",

**Comment by themattharris** [comment]
Yes, as ninjamonkno1 says, you can use the technique outlined in examples/images.php.

The image will still be uploaded to your server, and then sent to the Twitter API, but it will be loaded into the server's temporary store.
