### ISSUE TITLE
 Fatal error: Call to undefined function curl_init()

### ISSUE THREAD

**Issue by emmckenzie** [themattharris/tmhOAuth#151]
I am a newbie and learning about the Twitter API through 140.dev's ebook Single User Twitter OAuth Programming. When I run a php script that pulls from tmhOAuth I get the following error:  Fatal error: Call to undefined function curl_init()

I am sure it is something simple I am doing wrong, any ideas?

Thank you!

**Comment by willpower232** [comment]
This means you either need to install curl on your server or it has been disabled in your php configuration.

**Comment by themattharris** [comment]
as @willpower232 mentions, this error means your PHP installation is missing the require cURL library, more information on installing and configuring your installation with curl is available on the PHP website here: http://www.php.net/manual/en/curl.installation.php
