### ISSUE TITLE
Verify_ssl.php giving me Http response code 410

### ISSUE THREAD

**Issue by oosswwaalldd** [themattharris/tmhOAuth#154]
Hi Matt, 

I run a web site that allows to schedule tweets, since this weekend I have been getting http response code = 0 and a execution time of 10 secs (cURL timeout) in only like 20% of my tweet api call, I was reading some issues already closed and downloaded the last version of cacert.pem, when I run verify_ssl.php it says: 

```
"ERROR: There was a problem making the request
The HTTP response code was: 410"
```

Then, downgraded to my original file cacert.pem and it was the same error. I wanna let you know that I am still using you lib v0.7.1, I have not upgraded to the last one because my site is very dependent of this lib and I wanna first read all the changes made since this version, can you help me here please to identify what what be the problem, remember, only like 20% of the tweets attempt are giving this errors the rest is completing normally

What is wrong here? the libs was functioning at 100% before this weekend, can you help me here please?

Thanks!

**Comment by willpower232** [comment]
410 means you are probably using v1 of the api and it has to be v1.1 now. see where the URL is being set and make sure it says 1.1/ not just 1/

**Comment by oosswwaalldd** [comment]
Yes I noticed since I am using the old version of verify_ssl.php it was 1 instead 1.1, but my whole site api calls are adapted to v1.1, is there a version of verify_ssl.php to test cacert.pem with API v1.1? I think the problem I have, described above, has something to do with the ssl certificate, is there anything I could check to test the certificate? is it safe for me to download the latest cacert.pem and overwrite my current one?

Thanks

**Comment by willpower232** [comment]
I would double check the PHP to make sure it is using the correct api version as your main port of call. 410 means you connected to the server but what you were looking for is not there. If the certificate was preventing you from connecting then you would get a different message I guess.

I am working on the assumption that you should always download the latest certificate although if memory serves it has not been updated for a while.

**Comment by oosswwaalldd** [comment]
Look, my php is all good, it is working right now actually but as I wrote before, like 10~20% of the calls are giving HTTP response code 0 and exec time 10 s (this happens when there is a cURL timeout, I know it the hard way because Twitter has blocked me twice and this is the cURL behavior when that happens, not the case now though) but the rest is been tweeted ok with HTTP code 200.

Here is the code

```
    //make the API call
$tmhOAuth->request('POST', $tmhOAuth->url('1.1/statuses/update'), array('status' => $tweet));

//get code
$response_code = $tmhOAuth->response['code'];

//decode error
$error_array = json_decode($tmhOAuth->response['response']);
$error_str = $error_array->errors[0]->message;
```

but the $error_str is empty due to connection failure  i guess, what could be happening?

Thanks in advance!

**Comment by themattharris** [comment]
there's a number of things going on here, all of which i see as independent. i'll tackle the ones i see being discussed:
- using version 0.7.1: please upgrade to the latest version as soon as possible. the differences are subtle and i understand you want to verify things are ok first - but there are a number of improvements and reliability changes i made to support API 1.1 a lot better. that being said, 0.7.1 will still communicate with the api successfully.
- can you upgrade cacert.pem to the one supplied with v0.8.2: yes you can, there's no problem doing this.
- is there a version of verify_ssl.php that works with API 1.1: no there isn't. there wasn't anything gained by having that script over just calling the API. so i removed it. verify_ssl.php also uses api.twitter.com/1/help/test.json which wasn't carried over to API v1.1. instead, what you can use a combination of the verify_ssl.php and verify.php scripts like this: https://gist.github.com/themattharris/6273201
- 20% of my requests are failing with timeouts and a code of 0 but others succeeding: this sounds like you are using a cloud provider of some sort and requests are moving between IPs; and that some of those IPs have been blacklisted by Twitter. in those situations i would suggest building a retry into your script such that on timeout, you wait a few seconds and try again, and repeat a max of, say 5 times).

**Comment by oosswwaalldd** [comment]
Thanks Matt!, 

I will upgrade to the last version of the lib right away, my server has IP static, I will try the retry function in my script also.

Thanks again

**Comment by oosswwaalldd** [comment]
Sorry I reopen this issue, 

doing the cacert.pem verification with the suggested version of verify_ssl.php throwed this error:

```
ERROR: There was a problem making the request
The HTTP response code was: 400
```

any help to get it work?

**Comment by themattharris** [comment]
so these aren't ssl errors. if there were ssl errors the error message would be "ERROR: A verified SSL connection could not be successfully...."

a 400 indicates the API doesn't like what you sent it. you can dig into this a lot deeper by var_dumping the tmhOAuth object.

if you've upgraded tmhOAuth to v 0.8.0 or higher though you want to use this revision of the verify script: https://gist.github.com/themattharris/6273201

**Comment by oosswwaalldd** [comment]
Thanks, I will upgrade and hope this errors do not show up again
