### ISSUE TITLE
404 error while connection

### ISSUE THREAD

**Issue by wschwaiger** [themattharris/tmhOAuth#155]
Hi,

I am getting the following error when I try to connect via tmhOAuth to Twitter. I am on the latest version of your lib - any ideas? many thanks for your help.

Array
(
    [raw] => HTTP/1.1 404 Not Found
cache-control: no-cache, no-store, must-revalidate, pre-check=0, post-check=0
content-type: application/json; charset=utf-8
date: Wed, 04 Sep 2013 11:48:26 GMT
expires: Tue, 31 Mar 1981 05:00:00 GMT
last-modified: Wed, 04 Sep 2013 11:48:26 GMT
pragma: no-cache
server: tfe
set-cookie: lang=en
set-cookie: guest_id=v1%3A137829530639667478; Domain=.twitter.com; Path=/; Expires=Fri, 04-Sep-2015 11:48:26 UTC
status: 404 Not Found
strict-transport-security: max-age=631138519
x-access-level: read-write
x-frame-options: SAMEORIGIN
x-rate-limit-limit: 180
x-rate-limit-remaining: 172
x-rate-limit-reset: 1378295543
x-transaction: f64944378d00b500
Content-Encoding: gzip
Connection: close

{"errors":[{"message":"Sorry, that page does not exist","code":34}]}
    [headers] => Array
        (
            [HTTP/1.1 404 Not Found] => 
            [cache-control] => no-cache, no-store, must-revalidate, pre-check=0, post-check=0
            [content-type] => application/json; charset=utf-8
            [date] => Wed, 04 Sep 2013 11:48:26 GMT
            [expires] => Tue, 31 Mar 1981 05:00:00 GMT
            [last-modified] => Wed, 04 Sep 2013 11:48:26 GMT
            [pragma] => no-cache
            [server] => tfe
            [set-cookie] => Array
                (
                    [0] => lang=en
                    [1] => guest_id=v1%3A137829530639667478; Domain=.twitter.com; Path=/; Expires=Fri, 04-Sep-2015 11:48:26 UTC
                )

```
        [status] => 404 Not Found
        [strict-transport-security] => max-age=631138519
        [x-access-level] => read-write
        [x-frame-options] => SAMEORIGIN
        [x-rate-limit-limit] => 180
        [x-rate-limit-remaining] => 172
        [x-rate-limit-reset] => 1378295543
        [x-transaction] => f64944378d00b500
        [Content-Encoding] => gzip
        [Connection] => close
        [] => 
    )

[code] => 404
[response] => {"errors":[{"message":"Sorry, that page does not exist","code":34}]}
[info] => Array
    (
        [url] => https://api.twitter.com/1.1/statuses/user_timeline.json?count=3&include_entities=1&include_rts=1&screen_name=https%3A%2F%2Ftwitter.com%2FRichardJamesRow
        [content_type] => application/json; charset=utf-8
        [http_code] => 404
        [header_size] => 729
        [request_size] => 600
        [filetime] => -1
        [ssl_verify_result] => 20
        [redirect_count] => 0
        [total_time] => 0.455503
        [namelookup_time] => 0.003563
        [connect_time] => 0.109261
        [pretransfer_time] => 0.329247
        [size_upload] => 0
        [size_download] => 92
        [speed_download] => 201
        [speed_upload] => 0
        [download_content_length] => -1
        [upload_content_length] => 0
        [starttransfer_time] => 0.455413
        [redirect_time] => 0
        [certinfo] => Array
            (
            )

        [primary_ip] => 199.16.156.199
        [primary_port] => 443
        [local_ip] => 144.76.111.172
        [local_port] => 58687
        [redirect_url] => 
        [request_header] => GET /1.1/statuses/user_timeline.json?count=3&include_entities=1&include_rts=1&screen_name=https%3A%2F%2Ftwitter.com%2FRichardJamesRow HTTP/1.1
```

User-Agent: tmhOAuth 0.8.3-SSL - //github.com/themattharris/tmhOAuth
Host: api.twitter.com
Accept: _/_
Accept-Encoding: deflate, gzip
Authorization: OAuth oauth_consumer_key="9cA8IDjw9E5gtHoZd4VEw", oauth_nonce="2204705380bfc7fc15d6ef7690377253", oauth_signature="3XpVkEhegeMCqvBXNo3KmBm7EEc%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1378295322", oauth_token="163449158-sGpfqDiis45gxcYbnJpmkY3zCh77CHxlpn4DM5bP", oauth_version="1.0"

```
    )

[error] => 
[errno] => 0
```

)

**Comment by themattharris** [comment]
please include your code when asking for support. it helps me spot coding errors quicker.

in this case the Twitter API is telling you that the user timeline you are requesting does not exist. this is regardless of you using tmhOAuth or not.

looking at the request information you shared I can see this is because the screen_name you are asking for us a URL -- which is not correct.

`GET /1.1/statuses/user_timeline.json?count=3&include_entities=1&include_rts=1&screen_name=https%3A%2F%2Ftwitter.com%2FRichardJamesRow`

shows you have the screen_name set to https://twitter.com/RichardJamesRow instead of just RichardJamesRow

**Comment by wschwaiger** [comment]
argh, I am so sorry - thank you for your help. such a stupid mistake. sorry
