### ISSUE TITLE
Upload images to Twitter from a subdomain

### ISSUE THREAD

**Issue by Jaguar1** [themattharris/tmhOAuth#156]
Hi all,

first thank you Matt for your OAuth library. I'm using your tmhOAuth library to upload GIF files along with statuses to Twitter and it works nice this way:

'media[]' => "@{$image};type=image/gif;filename={$image}"

My question is: How to upload images from a SUBDOMAIN like "admin.mysite.com" when images were stored in a directory on the main domain "mysite.com/images"?

In this case it is not possible to use relative paths:
$image = './images/myfile.gif'; // image is not there

Instead I need to use the absolute path like:
$image = 'http://www.mysite.com/images/myfile.gif';

but as long as I know it is not permitted and it doesn't work.
Is there another way?

cheers,
Vladimir

**Comment by themattharris** [comment]
to publish images from URLs you need to download the image to the server you make the request to the Twitter API from. methods like file_get_contents (http://php.net/manual/en/function.file-get-contents.php) or fopen (http://php.net/manual/en/function.fopen.php) can be used to fetch the image (assuming the security settings in php.ini allow it).

hope that helps

**Comment by Jaguar1** [comment]
Thank you for the idea Matt, I've done it.
