### ISSUE TITLE
How to delete tweet

### ISSUE THREAD

**Issue by knowledgecorner** [themattharris/tmhOAuth#157]
hi
im using your "tmhOAuth" image tweets sucessfully updated by using following code
" $img = './'.$img;
$code = $tmhOAuth->request('POST', 'https://api.twitter.com/1.1/statuses/update_with_media.json',
array( 'media[]' => "@{$img}", 'status' => "$txt" ), true, true) ; "

im getting tweet id also but i want how to delete tweet and which method used for delete tweet.
Thanks in advance

**Comment by themattharris** [comment]
hey
you'll want the https://api.twitter.com/1.1/statuses/destroy/:id.json endpoint documented on dev.twitter.com here: https://dev.twitter.com/docs/api/1.1/post/statuses/destroy/%3Aid

hope that helps
