### ISSUE TITLE
Getting constant 403s trying to update_with_media

### ISSUE THREAD

**Issue by appweavers** [themattharris/tmhOAuth#159]
Hi Matt,

I have posting statuses working fine with tmhOAuth and I'm trying to add media to posts. I can post media with the photo_tweet.php example, but when I try the code myself I get nothing but 403s.

Here's my code after the include and tokens:

```
$image = file_get_contents('./images/PL195-8.png');
$status = "Test msg";
$name = "PL195";

$response = $tmhOAuth->user_request(array(
  'method' => 'POST',
  'url' => $tmhOAuth->url('1.1/statuses/update_with_media'),
  'params' => array(
    'media[]'  => "@{$image};type=image/png;filename={$name}",
    'status'   => $status,
    ),
  'multipart' => true,
    ));
```

I tried file_get_contents after reading your response to another question. I'm running this on a subdomain, although the image file is stored in the images directory of the subdomain. 

Any help would be greatly appreciated,

Nigel

**Comment by themattharris** [comment]
ah, yeah. so the file_get_contents was specifically for the situation that the file isn't local to the PHP script you are using to POST a tweet. in fact, even with that call you would still need to save the contents of the data returned from file_get_contents to a local temporary file before passing it's path as the $image variable. 

for your example you should find this one works for you: https://github.com/themattharris/tmhOAuthExamples/blob/master/cli/photo_tweet.php

if you are still having trouble, inspect the tmhOAuth->response['error'] variable to see if curl had a problem accessing the image.

**Comment by appweavers** [comment]
Thanks Matt. All is working fine now.

Nigel
