### ISSUE TITLE
LatestTweets not working with Widget Manager in SS 2.45

### ISSUE THREAD

**Issue by pcowley** [themattharris/tmhOAuth#160]
Since Twitter changed their policy and need to have login authed, I've been trying to find a way to make the exisiting widget work again - to no avail.
I have a site on 2.44 or 2.45 but not 3 anyhow. Widget manager doesn't seem able to add a LatestTweets widget I downloaded from here even though it shows up in the list of widgets that are available to be managed.
The widget manger mentioned in the readme appears to be for ss ver 3.01  - can someone confirm this (or not)?

If I install this into my 2.44 version I am worried I'd lose access to existing widgets already on the site.

Any help would be greatly appreciated

Cheers
Pete

**Comment by themattharris** [comment]
thanks for writing - unfortunately i'm not familiar with the code you are talking about. does it use tmhOAuth? this github project and it's issues are for that library only. 

for general api support i recommend instead visiting dev.twitter.com/discuss so twitter and community developers can help you out.
