### ISSUE TITLE
undefined function curl_init

### ISSUE THREAD

**Issue by ghost** [themattharris/tmhOAuth#163]
i am trying to write a simple twitter app that tweets using my account.when i try to run this app i get this error with the tmhOAuth library 0.8.3

Notice: Use of undefined constant CURL_HTTP_VERSION_1_1 - assumed 'CURL_HTTP_VERSION_1_1' in C:\wamp\www\madmensions.com\tmhOAuth.php on line 55

Fatal error: Call to undefined function curl_init() in C:\wamp\www\madmensions.com\tmhOAuth.php on line 758

**Comment by willpower232** [comment]
You need to enable curl in your wamp installation. Something like this should help:

http://stackoverflow.com/questions/13021536/how-to-enable-curl-in-wamp-server

If it is already enabled then make sure you have not disabled the function in the disable_functions directive in php.ini

**Comment by ghost** [comment]
Thanks men its working but now i run the app and get the response code
of 0 and tweet not posted.does that mean anything to you?

**Comment by ghost** [comment]
thanks men i have done it.works now but get this message of an error code when app runs error:0 and tweet not sent

**Comment by themattharris** [comment]
old ticket but in case it helps error 0 happens when curl fails to connect to the remote server (for some reason). check out the section titled "A note about security and SSL" in the readme for more guidance on what to do in this situation.
