### ISSUE TITLE
Will a new version of tmhOAuth be needed for the SSL certificate upgrade?

### ISSUE THREAD

**Issue by 140dev** [themattharris/tmhOAuth#167]
Twitter has made this announcement. 
https://dev.twitter.com/blog/rest-api-ssl-certificate-updates

Will this require an upgrade to tmhOAuth? Do you have an expected delivery date for this upgrade?

**Comment by themattharris** [comment]
thanks for checking on this.
if you use the included cacert.pem you'll be using the same SSL CA roots that Mozilla uses as of Sat Dec 29 20:03:40 2012 (the latest version) -- so things should be fine.
