### ISSUE TITLE
Using examples/search.php clarification

### ISSUE THREAD

**Issue by kenshin23** [themattharris/tmhOAuth#17]
Hi, first of all, thanks a lot for this library, it sure seems like it is easy enough to learn.
With that said, I have a question regarding the use of this example, as it's not very clear to me.

I'm keeping the code mostly as-is, except for the parameters:

```
$params = array(
  'q'        => 'Search Query',
//  'since_id' => 'Get results since this ID (or leave blank for earliest allowed)',
//  'pages'    => 'How many pages should be retrieved?',
//  'rpp'      => 'Results per page (default 15)',
//  'max_id'   => 'Max ID to accept. This isn\'t sent to Search but instead used to filter the received results',
//  'geocode'  => 'Geo co-ordinates (e.g. 37.781157,-122.398720,1mi)',
//  'lang'     => 'Restrict results to a specific language? (en,fr,de etc)'
);
```

If I load the page on my test server (question: is this meant to be loaded from a web browser?) I get this:
    Strict Standards: Non-static method tmhUtilities::read_input() should not be called statically in E:\xampp\htdocs\twitter2\examples\search.php on line 20
    Search Query: 
    Notice: Undefined index: pages in E:\xampp\htdocs\twitter2\examples\search.php on line 25
    Received page 1 http://search.twitter.com/search.json?page=1 There was an error. string(55) "{"error":"You must enter a query."}"

Any ideas on what I'm doing wrong? 
Again, thank you very much.

**Comment by themattharris** [comment]
Can you share all your code and also tell me which version of PHP you are running?

**Comment by kenshin23** [comment]
Certainly. PHP version is 5.3.8 (using XAMPP 1.7.7 on Windows 7) 
I actually think I found what the "problem" is and also answered my own question, but I've included a clarification.
Code (basically the same as the example but modified a bit):

```
<?php

date_default_timezone_set('GMT');

require '../tmhOAuth.php';
require '../tmhUtilities.php';
$tmhOAuth = new tmhOAuth(array());

$params = array(
  'q'        => 'Twitter API',
  'since_id' => '',
  'pages'    => '10',
  'rpp'      => '15',
//  'max_id'   => 'Max ID to accept. This isn\'t sent to Search but instead used to filter the received results',
//  'geocode'  => 'Geo co-ordinates (e.g. 37.781157,-122.398720,1mi)',
  'lang'     => 'es'
);

//This sets parameters if using this script through a CLI:
/*
foreach ($params as $k => $v) :
  $p[$k] = tmhUtilities::read_input("{$v}: ");
  if (empty($p[$k]))
    unset($p[$k]);
endforeach;

*/
/* Modification to get it to run without CLI: */
$p = array_filter($params);
//Removes "Notice: Undefined index: pages in..."
if( !isset($p['pages']) ):
    $p['pages'] = 1;
endif;
/*    End modification. */

$pages = intval($p['pages']);
$pages = $pages > 0 ? $pages : 1;
$results = array();

for ($i=$pages; $i > 0; $i--) {
  $args = array_intersect_key(
    $p, array(
      'q'        => '',
      'since_id' => '',
      'rpp'      => '',
      'geocode'  => '',
      'lang'     => ''
  ));
  $args['page'] = $i;

  $tmhOAuth->request(
    'GET',
    'http://search.twitter.com/search.json',
    $args,
    false
  );

  echo "Received page {$i}\t{$tmhOAuth->url}" . PHP_EOL;

  if ($tmhOAuth->response['code'] == 200) {
    $data = json_decode($tmhOAuth->response['response'], true);
    $results = array_merge($results, $data['results']);
  } else {
    $data = htmlentities($tmhOAuth->response['response']);
    echo 'There was an error.' . PHP_EOL;
    var_dump($data);
    die();
  }
}

foreach ($results as $result) {
  $date = strtotime($result['created_at']);
  $result['from_user'] = str_pad($result['from_user'], 15, ' ');
  $result['text'] = str_replace(PHP_EOL, '', $result['text']);
  echo "{$result['id_str']}\t{$date}\t{$result['from_user']}\t\t{$result['text']}" . PHP_EOL;
}

?>
```

```
```

**Comment by themattharris** [comment]
Yeah, that would do it. This example is there just to show how to retrieve results from the Twitter Search API. You could use it as a CLI script, or webpage called by a cron job. 

As this script could make multiple requests to the Twitter API (pages) I wouldn't allow it to be reached through a public URL.

There are a lot of optimizations you can make if you know what you want the script to do - for example, don't prompt for the values to search for. Your code does most of this but you can optimize a little more by doing something like this:

``` PHP
<?php

date_default_timezone_set('GMT');

require '../tmhOAuth.php';
require '../tmhUtilities.php';
$tmhOAuth = new tmhOAuth(array());

$pages = 5;
$args = array(
  'q'        => 'Twitter',
  'since_id' => '0',
  'rpp'      => '15',
  'lang'     => 'es',
);

$results = array();

for ($i=$pages; $i > 0; $i--) {
  $args['page'] = $i;

  $tmhOAuth->request(
    'GET',
    'http://search.twitter.com/search.json',
    $args,
    false
  );

  echo "Received page {$i}\t{$tmhOAuth->url}" . PHP_EOL;

  if ($tmhOAuth->response['code'] == 200) {
    $data = json_decode($tmhOAuth->response['response'], true);
    $results = array_merge($results, $data['results']);
  } else {
    $data = htmlentities($tmhOAuth->response['response']);
    echo 'There was an error.' . PHP_EOL;
    var_dump($data);
    die();
  }
}

foreach ($results as $result) {
  $date = strtotime($result['created_at']);
  $result['from_user'] = str_pad($result['from_user'], 15, ' ');
  $result['text'] = str_replace(PHP_EOL, '', $result['text']);
  echo "{$result['id_str']}\t{$date}\t{$result['from_user']}\t\t{$result['text']}" . PHP_EOL;
}

?>
```

As for the strict warning, it's because I don't declare the read_input method as a `static function` in the utilities file. It's there as a helper function so if strict compliance is something you need then adding `static` should silence the warning.

I'll mark this issue as closed as I think you have found the information you needed - if not feel free to comment and re-open the issue.
