### ISSUE TITLE
Timezone in new versions

### ISSUE THREAD

**Issue by trante** [themattharris/tmhOAuth#170]
I was using very old version 0.7.5 and each time I update tmhOAuth I was updating timezone from UTC to my local value.

 $this->config = array_merge(
      array(
        // default timezone for requests
        //'timezone'                   => 'UTC',

It seems like to timezone value in 0.8.3 ?
So does library gets system wide timezone ? How does timezone issues works now ?
Thank you very much

**Comment by themattharris** [comment]
the twitter api and tmhOAuth both use epoch seconds to communicate the timestamp with the server. in version 0.8.0 i removed the timezone support in response to #125. so, the library uses whatever default you set for your PHP instance in either your parent scripts, or php.ini file.

timezone issues can still be handled as, on error, the library can compare the difference between the local server time and the time of the twitter servers (by looking at the HTTP response headers).

**Comment by trante** [comment]
Thank you for detailed answer.
Best regards.
