### ISSUE TITLE
error with PHP 5.3

### ISSUE THREAD

**Issue by zuk22** [themattharris/tmhOAuth#175]
Hi.
When I change version of PHP from 5.2 to 5.3 the code below show an error - <b>Warning: Invalid argument supplied for foreach()</b>
 On PHP 5.2 it's working good.
<code>
$tmhOAuth = new tmhOAuth(array(  
                'consumer_key' => '********_',
                'consumer_secret' => '**_*****_',
                'user_token' => '**_*****_',
                'user_secret' => '**_******',
                'curl_ssl_verifypeer' => FALSE
            ));
$code    = $tmhOAuth->request('GET', $tmhOAuth->url('1.1/statuses/user_timeline'), array(
                    'screen_name' => $twitter_username,
                    'count' => $tweets_count
                ));  
                $response = $tmhOAuth->response['response'];
                $tweets = json_decode($response);
foreach($tweets as $tweet){
          $twit_text        = $tweet->text;
}
</code>

**Comment by themattharris** [comment]
i haven't tested the code but on inspection this looks like it might be because $tweets isn't an array but instead is NULL because the json_decode failed. 

can you validate that $code == '200' before attempting to decode the response?

**Comment by zuk22** [comment]
Hi. Thank's for answering me.
I tested the code and get error = '0'. 
It's occur when I change PHP version from 5.2 to 5.3 on my host

**Comment by themattharris** [comment]
that error usually means curl cannot open a connection to the remote server. in the past others have reported this happens when OpenSSL isn't correctly configured for your compiled PHP. 

what does $tmhOAuth->response['error'] contain?

**Comment by randallflagg34** [comment]
Hey, I'm having this same issue.
I'm on Hostgator running PHP 5.4 (I'm trying to switch to 5.2 but I need support from them to do that).

<code>My error is: 
["error"]=>
      string(24) "couldn't connect to host"
["errno"]=>
      int(7)
</code>
As far as I know my cacert.pem is being loaded, the **DIR** is working nice.
Most likelly is the PHP version, right?

**Comment by themattharris** [comment]
no, that error means curl cannot connect to the host specified (which defaults to api.twitter.com).

what does `php -i | grep OpenSSL` give you?
and can you `ping api.twitter.com`?

**Comment by randallflagg34** [comment]
Yes, I tried and indeed it was a problem from hostgator, it gave me Time Out. The same thing I tried from bluehost and had no problem.
I talked to the support team and they where kind enough to look into the issue and try to resolve stuffs, which they did. Just to have it in mind: it can be your hosting provider blocking something without noticing
