### ISSUE TITLE
Using proxies

### ISSUE THREAD

**Issue by alykhan** [themattharris/tmhOAuth#178]
I understand there is support for proxies but I'm unclear how to use the feature.

// support for proxy servers
        'curl_proxy'                 => false, 
        'curl_proxyuserpwd'          => false, 
        'curl_encoding'              => '',    

Where do we put the host for the proxy? 
is it something like this?

'curl_proxyuserpwd' => 'http://someproxyserver.com:username:password' ,

**Comment by themattharris** [comment]
the proxy support is more a 'proxy' in itself to the proxy settings of curl. 
the tmhOAuth configuration options match to the curl options of the similar name. for example, 'curl_proxy' matches to the cURL configuration option CURLOPT_PROXY, 'curl_proxyuserpwd' to CURLOPT_PROXYUSERPWD.

you can learn more about those options and what cURL expects you to do with them in the curl-setopt documentation: http://php.net/manual/en/function.curl-setopt.php
