### ISSUE TITLE
How to set encoding/charset ?

### ISSUE THREAD

**Issue by mtranchant** [themattharris/tmhOAuth#18]
Hi,

All accented characters are "destroyed" when requesting from/sending to Twitter.
Is there any solution to set the encoding to UT8, for example ?

Thanks for your big work, anyway :)

Regards

**Comment by mtranchant** [comment]
My fault.
Encoding is correct, the issue came from my HTML page.

**Comment by themattharris** [comment]
I'm just catching up after vacation and noticed you had this issue. Looks like you have it resolved though 

Glad you got it working!
