### ISSUE TITLE
'geocode' parameter doesn't seem to work for search/tweets.json

### ISSUE THREAD

**Issue by Brade** [themattharris/tmhOAuth#181]
Specifying a geocode param as discussed here: https://dev.twitter.com/rest/reference/get/search/tweets

Example:

```
$twitobj->request('GET', 'https://api.twitter.com/1.1/search/tweets.json', array('q' => '#' . $term, 'lang' => 'en', 'count' => 100, 'geocode' => '29.950844,-90.081249,20mi'));
```

'geocode' doesn't seem to get passed at all. I just get a bunch of tweets that aren't geocoded.

**Comment by themattharris** [comment]
when you say the geocode parameter doesn't seem to be getting passed - was it missing from the url being sent by tmhOAuth?

you can see the url being sent using this: `var_dump($twitobj->response['info']['url']);`

tmhOAuth doesn't do any filtering itself so, if you see the geocode parameter in the URL being sent to the Twitter API, perhaps this is a problem with the search/tweets api endpoint?

**Comment by Brade** [comment]
Yeah, after looking at this more closely, it was an issue w/ Twitter's API being very liberal if a tweet isn't specifically geolocated (as well as including retweets by default unless you include " -RT" in the search term query, a fact not mentioned anywhere in the docs)

**Comment by themattharris** [comment]
ok cool. i'm going to close this out then as tmhOAuth is passing the parameter.
