### ISSUE TITLE
Implode in tmhOAuth::create_nonce()

### ISSUE THREAD

**Issue by reedy** [themattharris/tmhOAuth#20]
```
  $this->config['nonce'] = md5(substr($prefix . implode($sequence), 0, $length));
```

Can you add the $glue parameter so it is more consistent with the more usual "string implode ( string $glue , array $pieces )"

Thanks!

**Comment by themattharris** [comment]
Yeah that would be the preferred way of doing it. I'll add that into the next update. Thanks!

**Comment by themattharris** [comment]
Just pushed that change with v0.60 so i'm closing this issue. Thanks again. (Props are in the readme ;) )
