### ISSUE TITLE
Kill trailing ?>

### ISSUE THREAD

**Issue by reedy** [themattharris/tmhOAuth#21]
They're not needed unless you're stopping the PHP block, and dependant on usage, they can cause stupid header already sent errors in PHP

Would you mind removing them from both tmhOAuth.php and tmhUtilities.php?

Saves having to remember to remove them when pulling them in upstream...

Thanks!

**Comment by themattharris** [comment]
I know the Zend Framework's coding practices say the closing tag is never permitted so i'm not against doing this.
I'll add this as something for the 0.61 release

**Comment by reedy** [comment]
Great :)

**Comment by themattharris** [comment]
Pushed v0.61 just now, and that change is in there. 
Thanks!
