### ISSUE TITLE
r60 seems to be causing a glitch somewhere

### ISSUE THREAD

**Issue by varnent** [themattharris/tmhOAuth#22]
We're using a basic clone of examples / tweet.php and as of r60 - having no luck with sending tweets.  Reverting to r57 (with Reedy's tweak applied as well) seems to return behavior back to normal.

Any ideas on the differences between the two that may need a tweak on my part?
http://svn.wikimedia.org/svnroot/mediawiki/trunk/extensions/TweetANew/TweetANew.body.php

**Comment by themattharris** [comment]
r60 turns on SSL host verification. Can you run examples/verify_ssl.php and tell me if it's successful. Also, r60 saves the error response (if any). Can you (in a debug mode) run your code but at the end dump $tmhOAuth->response out. The extra info should help work out what's happening

**Comment by varnent** [comment]
Nevermind - discovered what the problem was.  When we updated to the new version, we didn't add the cacert.pem file to the lib folder with the other two tmhOAuth files - whoops - seems to be working now.  :)

**Comment by themattharris** [comment]
The security thing is tricky but necessary to ensure the SSL connection is verified.
Either way, glad you got that solved - and thanks for letting me know!
