### ISSUE TITLE
small improvement

### ISSUE THREAD

**Issue by kronenthaler** [themattharris/tmhOAuth#3]
Hi, nice work with this library, very easy to use and works as you could expect. Nevertheless, I propose to you a very small change to make the usage of the code more compact. 

first: at the line 350: CHANGE to: return $this->curlit($multipart);
second: function curlit, make it "return $code" at the end.

With this change you could process in the same "if" the return code of the request you just made, making it more compact and even more readable (IMO).

Thanks for share this class.

**Comment by themattharris** [comment]
This has been incorporated into v0.4. Thanks!
