### ISSUE TITLE
Change Profile Picture Failed at images.php

### ISSUE THREAD

**Issue by masbog** [themattharris/tmhOAuth#35]
i want to change my avatar but result from twitter like this 

{"request":"\/1\/account\/update_profile_image.json","error":"Invalid Unicode value in one or more parameters"}

some body can resolve this issue?

**Comment by themattharris** [comment]
Heya,
thanks for asking this here.
Can you share the code you are using for this (remember to remove things like the oauth and consumer secrets before pasting).

**Comment by masbog** [comment]
i use an original source images.php, just insert my secret token and bla bla bla.. i have your repo by git clone your repo...

**Comment by themattharris** [comment]
OK, interesting. Can you add:
var_dump($tmhOAuth);
to the end of the script and let me know what the output looks like. Remember to remove the sensitive information like user_secret and consumer_secret and signingkey.

**Comment by ghost** [comment]
I have same problem. But I don't see any mistake. Nothing happed. And Image didn't changed.

**Comment by ghost** [comment]
$vardump says:
Conten'... (length=618)
      'error' => string 'Operation timed out after 10015 milliseconds with 0 bytes received' (length=66)
      'errno' => int 28

**Comment by themattharris** [comment]
Be default tmhOAuth is set to timeout the request after 10 seconds. You can bump this up by adding the `curl_timeout` parameter to the tmhOAuth instantiation. For example, to set the timeout to 15 seconds you would do this:

```
$tmhOAuth = new tmhOAuth(array(
  'consumer_key'    => 'YOUR_CONSUMER_KEY',
  'consumer_secret' => 'YOUR_CONSUMER_SECRET',
  'user_token'      => 'A_USER_TOKEN',
  'user_secret'     => 'A_USER_SECRET',
  'curl_timeout'    => 15,
));
```

**Comment by themattharris** [comment]
did the code above help?

**Comment by ghost** [comment]
yes,thanx
