### ISSUE TITLE
Re-tweets retrieval

### ISSUE THREAD

**Issue by oosswwaalldd** [themattharris/tmhOAuth#37]
I want to implement in my Twitter app a functionality where a logged in user can see a list of user who has re-tweeted any of the tweets made from the logged in user, is there an API to do this? there is one and it retrieves the re-tweets of a given status id but not on the user id.

Thanks in advance for any help

**Comment by themattharris** [comment]
Hey,

This is a good question to ask on the Twitter API developers forum: https://dev.twitter.com/discussions
To start you off though, have you thought about using the /1/statuses/retweets_of_me call? 
    https://dev.twitter.com/docs/api/1/get/statuses/retweets_of_me

**Comment by oosswwaalldd** [comment]
Yes my mistake, I already accomplish the feature in my app with statuses/retweets_of_me.

Thanks anyway!
