### ISSUE TITLE
Retrieving Direct Messages

### ISSUE THREAD

**Issue by nateh** [themattharris/tmhOAuth#38]
Hi This line does not do it

$code = $tmhOAuth->request('GET', $tmhOAuth->url('1/direct_messages.json'), array(
  'data' => 'count=1&page=1'));

Would appreciate help if possible

**Comment by themattharris** [comment]
Hey nateh,

When requesting direct messages it's important for your OAuth application has the correct permissions. Twitter requires your application has Read/Write and Direct Message access to be able to read a users DMs. You can check your application has this permission on it's settings page linked to from https://dev.twitter.com/apps . If you have to change the permission level remember to request an access token again.

More information on the permission model is on the developer resources site: https://dev.twitter.com/docs/application-permission-model

The other thing to note is your use of the tmhOAuth request. Any API request parameters must be sent as key => value pairs in the params array, not as data. In your case this means the line should look like:

```
$code = $tmhOAuth->request('GET', $tmhOAuth->url('1/direct_messages.json'), array(
    'count' => 1,
    'page' => 1'
));
```

Last thing, if you are getting errors please include the response body and HTTP codes which come back from the Twitter API. Knowing the error message which comes back can help me provide more accurate information.

Best
@themattharris

**Comment by nateh** [comment]
Thank you Matt

Apologies I was away.

Yes I'm now getting a response but I had to drop the json in

url('1/direct_messages.json')

It returns json in any case.

Thanks for the help
