### ISSUE TITLE
Proxy needed

### ISSUE THREAD

**Issue by juanchorossi** [themattharris/tmhOAuth#4]
Hey! Awesome library, works great! I've added a few lines so it can proxy requests:
- On the constructor: 'curl_proxy'                  => false,
- On the cURL handler init: curl_setopt($c, CURLOPT_PROXY, $this->config['curl_proxy']);

It 'd be great to have this option of the further releases!
Thanks!

**Comment by themattharris** [comment]
This has been incorporated in v0.4. Thanks!

**Comment by juanchorossi** [comment]
Thanks! :)
