### ISSUE TITLE
Declaring functions as static

### ISSUE THREAD

**Issue by trante** [themattharris/tmhOAuth#40]
Can you declare functions as static methods? Because most of the methods are called statically..

Else i will put "error_reporting(E_ALL ^ E_STRICT);" in code.

Or do you suppress STRICT warnings?

**Comment by themattharris** [comment]
can you provide an example of the error log you are seeing?

when I set error_reporting(E_ALL); and run the examples i'm not getting any error entries.

**Comment by themattharris** [comment]
hey trante, can you provide the error log that's showing the strict errors. thanks.

**Comment by trante** [comment]
I couldn't reproduce the problem.
If i can reproduce i would open again.
Thank you.
