### ISSUE TITLE
Callback address

### ISSUE THREAD

**Issue by trante** [themattharris/tmhOAuth#41]
Can we set oauth's callback address by using "oauth_callback"?

I read "Desktop applications only support the oauth_callback value" 
But "POST oauth/request_token" says "oauth_callback required"

So if we set "oauth_callback", does this suppresses the callback address in application's settings value?
Did i miss something can you give more information?

Thank you

**Comment by themattharris** [comment]
Yes, oauth_callback can be set at runtime -- and should be for OAuth 1.0a. For backwards compatibility with OAuth 1.0 apps Twitter supports not setting it but it's discouraged.

When you pass the oauth_callback parameter in the oauth/request_token request, the value in the application's settings is ignored.

For more information on how OAuth works with Twitter's APIs I recommend posting a discussion on https://dev.twitter.com/discussions

**Comment by themattharris** [comment]
Hey trante, did the above answer your question? if so, could you close the issue - thanks.

**Comment by trante** [comment]
Yes, sorry. thank you
