### ISSUE TITLE
Rate limit check

### ISSUE THREAD

**Issue by trante** [themattharris/tmhOAuth#45]
I checked examples to find "rate limit check".
I only find one example in examples/friends.php

But it checkes rate limit after a "1/friends/ids" request.
Is it not better to check rate limit before making a request.

Thank you

**Comment by themattharris** [comment]
I'm using the response headers from that request to decide if it's ok to make requests again or not.

If you think the rate limit could have been exhausted before the request you could call `/1/account/rate_limit_status.json` first.

**Comment by trante** [comment]
Ok thank you
