### ISSUE TITLE
issue with update_with_media method.

### ISSUE THREAD

**Issue by erratik** [themattharris/tmhOAuth#48]
Hi, 

I'm trying to update a status with a picture. But I keep getting stuck at error 26. I'm using this in a drupal7  local environment.
Here is the function:

<code>
function moxies_twitter_updates_status_with_media($tweet,$user,$replyID=NULL,$media){    

```
require 'tmhOAuth/tmhOAuth.php';
require 'tmhOAuth/tmhUtilities.php';

$tmhOAuth = new tmhOAuth(array(
  'consumer_key'    => CONSUMER_KEY,
  'consumer_secret' => CONSUMER_SECRET,
  'user_token'      => moxies_twitter_get_oauth_token($user), 
  'user_secret'     => moxies_twitter_get_auth_token_secret($user),
    'host'          => "upload.twitter.com"
));
// connection is good!

$image = image_style_url('large', $media->uri);  // http://staging.simplesimple.ca:8081/phase2/sites/default/files/styles/large/public/lips_2.jpg
$mime = $media->filemime; // image/jpeg
$result = $tmhOAuth->request(
  'POST',
   'https://upload.twitter.com/1/statuses/update_with_media.json',
  array(
    'media[]'  => "@{$image}",
    'status'   => 'Picture time',
  ),
  true, // use auth
  true  // multipart
);

if ($result == 200) {
  tmhUtilities::pr(json_decode($tmhOAuth->response['response']));
} else {
  tmhUtilities::pr($tmhOAuth->response['response']);
}

dsm($tmhOAuth->response); // Forcing the output of the response through Drupal messaging because the tmhUtilities are not outputting anything :/
```

}
## </code>

Once this runs, this is my response:
<code>
Array
(
    [code] => 0
    [response] => 
    [info] => Array
        (
            [url] => https://upload.twitter.com/1/statuses/update_with_media.json
            [content_type] => 
            [http_code] => 0
            [header_size] => 0
            [request_size] => 0
            [filetime] => -1
            [ssl_verify_result] => 0
            [redirect_count] => 0
            [total_time] => 0.343
            [namelookup_time] => 0.031
            [connect_time] => 0.093
            [pretransfer_time] => 0.343
            [size_upload] => 0
            [size_download] => 0
            [speed_download] => 0
            [speed_upload] => 0
            [download_content_length] => -1
            [upload_content_length] => -1
            [starttransfer_time] => 0
            [redirect_time] => 0
            [certinfo] => Array
                (
                )

```
        [redirect_url] => 
    )

[error] => couldn't open file "/signature-johan.gif"

[errno] => 26
```

)
</code>
I've tried with different types of filetypes and I keep getting this same error. Am I missing something really simple here?

**Comment by erratik** [comment]
We were using the URL to the image, not the path on the machine. So it works now!

**Comment by arjun231005** [comment]
I have the same issue.. can you please tell me how did you solve it... thank you
