### ISSUE TITLE
Warnings from IDE

### ISSUE THREAD

**Issue by trante** [themattharris/tmhOAuth#51]
I use phpStorm IDE.
And it gives many warnings in my code. Most of them because of **response** and **request**
Can you recommend me a way to discard tmhOAuth based warnings?

`$code=$tmhOAuth->request('GET', $tmhOAuth->url('1/account/totals') );`
Warning: 'void' method 'request' result used

`$responseData = json_decode($tmhOAuth->response['response'],true);`
Field 'response' not found in class tmhOAuth

**Comment by themattharris** [comment]
this is a duplicate of issue#47 so i'm going to close it

**Comment by trante** [comment]
I'm sorry i missed.
