### ISSUE TITLE
Streaming api with follow is not working?

### ISSUE THREAD

**Issue by karupse** [themattharris/tmhOAuth#53]
I am using track keyword with streaming.php...
It works fine. It tracks the tweets.
But i am just using follow param it shows empty string as tweet.
What is the issue here?

**Comment by themattharris** [comment]
remember the streaming API only sends tweets sent by the user after you connect to the streaming API -- and only if the user hasn't marked their account as protected - could that be what's happening for you?

**Comment by themattharris** [comment]
closing this one out as there hasn't been a follow up response from the original author in 2 months
