### ISSUE TITLE
Character encoding in status

### ISSUE THREAD

**Issue by timersys** [themattharris/tmhOAuth#55]
I cant make it work with special characters as á é í ñ ,etc.

A while ago with another library i fixed by doing utf8_encode() to the status message but here its just removing the characters. Any clues?

**Comment by themattharris** [comment]
interesting, i've tried this before with my library (without modification) and it submitted successfully. do you mind sharing the code snippet you are using to send those characters. i used:

```
$code = $tmhOAuth->request('POST', $tmhOAuth->url('1/statuses/update'), array(
  'status' => 'sending á é í ñ'
));
```

which worked without trouble. here's a snippet of the response:

```
"text":"sending \u00e1 \u00e9 \u00ed \u00f1""
```

**Comment by themattharris** [comment]
closing this one out. if my comment above didn't help please let reopen letting me know what isn't working.

**Comment by spuckylucky** [comment]
Hi, first of all thanks for the library and the example code wich is very handy. Everything works fine and it updates status smoothly, unless the status contains certains characters. The thing goes far beyond my understanding and i'd really appreciate any suggestion. 
The characters are è and é and the error message is "could not authenticate with oauth" but sometimes is "invalid unicode character". I really don't understand what triggers the former and what the latter, but i'm sure that are those two characters.

**Comment by oosswwaalldd** [comment]
Hi!, I am having the same problem, the issue occurs when I get direct messages and then trying to post them, when there is a special character like described above, Twitter returns a 403 error, wrong credentials, but that does not happen. 

Thanks a lot for taking the time to debug this.

**Comment by spuckylucky** [comment]
I feel so stupid but the problem was that the message has to be utf8 encoded, 'status' => utf8_encode($your_tweet). I hope this will solve your problem too.
