### ISSUE TITLE
Streaming API output to web browser

### ISSUE THREAD

**Issue by oosswwaalldd** [themattharris/tmhOAuth#58]
Hi Matt, 

is there any way to output (handle) the output of the streaming api (streaming.php) to direct it to a web browser? I mean, currently it outputs to console very well as I tested it, but when I run it in Chrome it does not.

Is streaming API rate limited by the same REST API rules?

I would appreciate some help here!, thanks!

**Comment by themattharris** [comment]
hey there,
the streaming api isn't really built for use in a web browser - at least not the way you suggest you are trying to. if you want to stream content to the web browser i would instead recommend researching the concept of web sockets.

alternatively, consume the streaming API on your server and then have your browser poll your server for a processed response.

to answer your other question, the streaming api is a single, long poll connection that is kept open. as such the 'polling' rate limits of the REST API do not apply. instead the streaming api rate limits by the volume of tweets it delivers. more information on this is on the developer resources site: https://dev.twitter.com/docs/faq#6861

closing this out as it's not an issue with the library. if you have any more question on how to implement a feature like this i recommend starting a conversation on https://dev.twitter.com/discuss
