### ISSUE TITLE
DELETE method fails with Incorrect signature

### ISSUE THREAD

**Issue by yusuke** [themattharris/tmhOAuth#6]
## This is the snippet of my code which fails with "{"request":"\/1\/twtr_A\/37157616\/members.json","error":"Incorrect signature"}".

```
$twitter->request("DELETE", $twitter->url("1/$screenName/" . $id . "/members")
  , array("id" => $userId), "");
```

---

Complete code is available here: https://gist.github.com/853156

**Comment by themattharris** [comment]
Fixed in v0.4. Thanks!
