### ISSUE TITLE
Support request: 404 error after retweet action

### ISSUE THREAD

**Issue by trante** [themattharris/tmhOAuth#60]
I can successfuly post statuses but I'm stuck with retweet.

I'm trying to retweet a tweet by using Twitter API and tmhOauth with following snippet:

`$tmhOAuth = new tmhOAuth(array( 'consumer_key'    => YOUR_CONSUMER_KEY,
                      'consumer_secret' => YOUR_CONSUMER_SECRET,
                       'user_token'      => $atoken1,
                      'user_secret'     => $atoken2, ));
$code = $tmhOAuth->request('POST', $tmhOAuth->url('1/statuses/retweet'),
                   array('id' => '223136515088318466' ));`
But this code gives following error:

`[errors] => Array
    (
        [0] => Array
            (
                [message] => Sorry, that page does not exist
                [code] => 34
            )
    )`

But I can see that status exists: https://twitter.com/Sekban_iCemil/status/223136515088318466

I'm pretty sure that consumer key and secret is correct, and user token and secret is authorized by user.

What do I miss ?

**Comment by themattharris** [comment]
for retweets the tweet ID should be sent as part of the URL, not as a param.

**Comment by trante** [comment]
this solved as you noted
    $code = $tmhOAuth->request('POST', $tmhOAuth->url('1/statuses/retweet/223136515088318466'));

Thank you very much for help.

**Comment by themattharris** [comment]
glad that fixed it! thanks for letting me know it worked
