### ISSUE TITLE
Upload with Url

### ISSUE THREAD

**Issue by dafinley** [themattharris/tmhOAuth#61]
Is there a way to upload a photo with a url that is not on the local hardrive?  For example facebook.com/favicon.ico  <-- It is a url that is web accessible.

**Comment by themattharris** [comment]
hey,
tmhOAuth wraps libcurl and uses it to send content to the twitter API -- this means it has the same restrictions/requirements as libcurl. the twitter api also does not support uploading directly from a url, and requires the image you wish to publish be sent as the POST body of the request.

to upload an image from a url you would need to first download the contents of that url to your server, and then send that downloaded content to the twitter api. 

closing this out as i think it answers your question. if not, drop a comment afterwards and we can review.

**Comment by dafinley** [comment]
You might be able to help. I was able to download the photo to my server,
but Im still not able to upload the photo to twitter https://dev.twitter.com/discussions/9424
