### ISSUE TITLE
Failed to validate oauth signature and token 

### ISSUE THREAD

**Issue by nalagg** [themattharris/tmhOAuth#62]
im getting this on oAuth,   examples/auth.php

heres my varDump
object(tmhOAuth)#1 (5) {
  ["params"]=>
  array(0) {
  }
  ["headers"]=>
  array(0) {
  }
  ["auto_fixed_time"]=>
  bool(false)
  ["buffer"]=>
  NULL
  ["config"]=>
  array(28) {
    ["user_agent"]=>
    string(56) "tmhOAuth 0.621+SSL - //github.com/themattharris/tmhOAuth"
    ["use_ssl"]=>
    bool(true)
    ["host"]=>
    string(15) "api.twitter.com"
    ["consumer_key"]=>
    string(21) "*********************_"
    ["consumer_secret"]=>
    string(41) "**_************************************_"
    ["user_token"]=>
    string(50) "**_**********************************************_"
    ["user_secret"]=>
    string(42) "**_*************************************"
    ["force_nonce"]=>
    bool(false)
    ["nonce"]=>
    bool(false)
    ["force_timestamp"]=>
    bool(false)
    ["timestamp"]=>
    bool(false)
    ["oauth_version"]=>
    string(3) "1.0"
    ["oauth_signature_method"]=>
    string(9) "HMAC-SHA1"
    ["curl_connecttimeout"]=>
    int(30)
    ["curl_timeout"]=>
    int(10)
    ["curl_ssl_verifyhost"]=>
    int(2)
    ["curl_ssl_verifypeer"]=>
    bool(true)
    ["curl_cainfo"]=>
    string(85) "/var/www/myDomain/twitter/tmhOAuth-d0b0bc6/cacert.pem"
    ["curl_capath"]=>
    string(74) "/var/www/myDomain/twitter/tmhOAuth-d0b0bc6"
    ["curl_followlocation"]=>
    bool(false)
    ["curl_proxy"]=>
    bool(false)
    ["curl_proxyuserpwd"]=>
    bool(false)
    ["curl_encoding"]=>
    string(0) ""
    ["is_streaming"]=>
    bool(false)
    ["streaming_eol"]=>
    string(2) "
"
    ["streaming_metrics_interval"]=>
    int(60)
    ["as_header"]=>
    bool(true)
    ["debug"]=>
    bool(false)
  }
}

**Comment by themattharris** [comment]
hey there,
it looks like you are specifying the user_token and user_secret when creating the $tmhOAuth object. when performing auth you should only be specifying the consumer_key and consumer_secret. this is because the auth.php script is there to help you get a user_token and user_secret. if you already have them you don't need to go through that flow.

let me know if removing the user_secret and user_token (or setting them to '') fixes the auth script for you.

**Comment by nalagg** [comment]
setting the user_token and user_secret to '' did the trick

```
'user_token' => '',
'user_secret' => ''
```
