### ISSUE TITLE
Unfollow User

### ISSUE THREAD

**Issue by garyw75** [themattharris/tmhOAuth#68]
I was wondering if an example on how to unfollow a user could be added?

**Comment by themattharris** [comment]
hey garyw75, i'll get one of those added for you.
i'm in the process of moving the examples to their own repository: https://github.com/themattharris/tmhOAuth-examples and will the example in there.

**Comment by themattharris** [comment]
hey garyw75,

i've added an example showing how to use this here: https://github.com/themattharris/tmhOAuth-examples/blob/master/unfollow.php

hope that helps!
