### ISSUE TITLE
"Problem with the SSL CA cert (path? access rights?)"

### ISSUE THREAD

**Issue by lior2007** [themattharris/tmhOAuth#69]
Hi,

I'm using tmhoath to twit images but I cannot connect (although it used to work a few month ago). When I tried running verify_ssl.php (https://github.com/themattharris/tmhOAuth/blob/master/examples/verify_ssl.php) it returned "Problem with the SSL CA cert (path? access rights?)" (and this is the same error I receive when I try to twit). Any suggestions on how to resolve this?

Thanks,
Lior

**Comment by themattharris** [comment]
hey llor2007,
apologies for the slow response to your question. the error you are getting suggests the cacert.pem file included in the tmhOAuth repository could not be found. 

double check cacert.pem is in the same folder as the tmhOAuth.php script. if not, set the curl_cainfo and curl_capath configuration attributes so that they point to the place where cacert.pem is. for example:

```
$tmhOAuth = new tmhOAuth(array(
  'consumer_key'    => 'YOUR_CONSUMER_KEY',
  'consumer_secret' => 'YOUR_CONSUMER_SECRET',
  'user_token'      => 'A_USER_TOKEN',
  'user_secret'     => 'A_USER_SECRET',
  'curl_cainfo'     => dirname(__FILE__) . '/cacert.pem',
  'curl_capath'     => dirname(__FILE__),
));
```

**Comment by lior2007** [comment]
Hi Matt,

It worked!! Thanks =)

Regards,
Lior Dagan

Sent from my iPhone

On 4 בספט 2012, at 06:49, Matt Harris notifications@github.com wrote:

hey llor2007,
apologies for the slow response to your question. the error you are getting
suggests the cacert.pem file included in the tmhOAuth repository could not
be found.

double check cacert.pem is in the same folder as the tmhOAuth.php script.
if not, set the curl_cainfo and curl_capath configuration attributes so
that they point to the place where cacert.pem is. for example:

$tmhOAuth = new tmhOAuth(array(
  'consumer_key'    => 'YOUR_CONSUMER_KEY',
  'consumer_secret' => 'YOUR_CONSUMER_SECRET',
  'user_token'      => 'A_USER_TOKEN',
  'user_secret'     => 'A_USER_SECRET',
  'curl_cainfo'     => dirname(**FILE**) . '/cacert.pem',
  'curl_capath'     => dirname(**FILE**),
));

 —
Reply to this email directly or view it on
GitHubhttps://github.com/themattharris/tmhOAuth/issues/69#issuecomment-8251807.

**Comment by themattharris** [comment]
Awesome, thanks for letting me know.
i'll close this issue out as it's resolved for you.
