### ISSUE TITLE
calling 1/help/test.json fails with "Could not authenticate with OAuth"

### ISSUE THREAD

**Issue by yusuke** [themattharris/tmhOAuth#7]
## The following code fails with {"request":"\/1\/help\/test.json","error":"Could not authenticate with OAuth."}:

require "./tmhOAuth.php";
$twitter = new tmhOAuth(array());

$twitter->request("GET", $twitter->url("1/help/test"));
## print $twitter->response["response"];

reproducer: https://gist.github.com/854361

**Comment by themattharris** [comment]
Doing what you are doing will initialize the array with an empty consumer key, secret, user token and secret. By default request will always attempt to authenticate. If you don't want to authenticate you need to modify the call to request like this:
    $twitter->request("GET", $twitter->url("1/help/test"), array(), false);
