### ISSUE TITLE
Problem with the date?

### ISSUE THREAD

**Issue by iamctodd** [themattharris/tmhOAuth#70]
Warning: strtotime(): It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'America/New_York' for 'EDT/-4.0/DST' instead in /path/to//tmhOAuth/examples/streaming_advanced.php on line 37

**Comment by themattharris** [comment]
thanks for sharing this. those warnings can be annoying so, to make it easier for everyone, including me :), i'll add a configuration option to tmhOAuth and make it so it sets the default timezone itself.

**Comment by themattharris** [comment]
i've added this config options and feature into 0.7.0. props given in readme and the commit message
