### ISSUE TITLE
Using tmhOAuth as delegate?

### ISSUE THREAD

**Issue by strlng** [themattharris/tmhOAuth#71]
I am trying to figure out how to set up a delegate service with tmhOAuth. The client sends the request to my web app from a Twitter client and I need to verify the sender's identity from the headers in their request. I cannot figure out how to get this done. Is this not possible with the library or am I missing something?

**Comment by themattharris** [comment]
which stage of the request do you want to use the library for:
- generating the verify headers?
- sending the verify headers to twitter?
- something else?

it can do any of them so let me know which you are interested in and i'll get an example put together for you.

**Comment by strlng** [comment]
I figured it out. Thanks though. I'm using your library in this Wordpress plugin: http://wordpress.org/extend/plugins/twitter-media-endpoint/

**Comment by themattharris** [comment]
excellent, glad you worked it out! and for sharing your solution.
