### ISSUE TITLE
Streaming API stops receiving data

### ISSUE THREAD

**Issue by ghost** [themattharris/tmhOAuth#74]
Hi,
since a few weeks my application starts regularly and receives live tweets for a while (5/10/30 minutes) and then suddenly stops without giving me any feedback.
If i restart it again the cycle repeats.

Is there any known problem? The app used to work perfectly fine

Thanks in advance

**Comment by themattharris** [comment]
there's nothing i'm aware of that would affect the scripts ability to consume from the streaming API.
have you asked if there are any issues with the Streaming API on dev.twitter.com/discuss?

one thing to check though - do you process the response of the streaming API using the same process you use to listening to it?
it's recommended you consume in one script, pass that to a file or queue, and process in a second script. this is to prevent your script causing your streaming API connection to fall behind real-time.

**Comment by ghost** [comment]
I opened a discussion here: https://dev.twitter.com/discussions/10446 a while back

I just put the data in a database for later processing, the receiving script is very simple: http://nopaste.me/paste/16046206055085604b46763

**Comment by themattharris** [comment]
did you make any progress in the forums with this issue?
