### ISSUE TITLE
problems with tmhOAuth

### ISSUE THREAD

**Issue by briggl** [themattharris/tmhOAuth#75]
When I try to use your tmhOAuth.php library, I get this error:

[10-Sep-2012 13:06:20] PHP Parse error:  syntax error, unexpected T_CONST, expecting T_OLD_FUNCTION or T_FUNCTION or T_VAR or '}' in /home/briggl/public_html/oauth/tmhOAuth.php on line 15

What am I doing wrong.
I have included the library in the php file and it gets the error as soon as it tries to use the library.

**Comment by themattharris** [comment]
hey briggl,

what version of PHP are you using?
and how are you including the tmhOAuth.php in your script?

**Comment by briggl** [comment]
The version of PHP that my web host uses is 4.4.9

I am using this statement to include your library:

```
include("http://briggl.com/oauthfolder/tmhOAuth.php");
```

This include seems to work because it gets an error with your tmhOAuth.php
file, not with the file being missing or anything like that.

lee

**Comment by briggl** [comment]
I have updated to PHP5 (version 5.2.17) and the previous error has gone away.

Now, when I test the code, I get a 401 response. (I have double-checked the keys)

Here is the code I am using (with keys replaced by 00000)

//set the message to tweet
    $tweet_text = "Message to Tweet";

//Matt Harris OAuth library to make the connection
    require_once('../oauthfolder/tmhOAuth.php');

//Set the authorization values
    $connection = new tmhOAuth(array(
        'consumer_key' => '00000',
        'consumer_secret' => '00000',
        'user_token' => '00000-00000',
        'user_secret' => '00000',
    ));

//Make the API call
    $connection->request('POST',
        $connection->url('1/statuses/update'),
        array('status' => $tweet_text));

```
return $connection->response['code'];
```

**Comment by themattharris** [comment]
glad upgrading to PHP 5 solved the first issue for you. the library is only tested for compatibility to PHP 5 so knowing there are issues with PHP 4 are not surprising -- but also helpful to note (i'll update the readme saying PHP 5 is required now I think).

for the second issue, what is the contents of `$connection->response['raw'];`? it should contain an explanation as to why the 401 error was returned by the Twitter API.

**Comment by briggl** [comment]
I think I see the problem... "Read-only application cannot POST" at the end of the output. I guess I missed the check box when I set up the app. Am I correct?

HTTP/1.1 401 Unauthorized Date: Wed, 12 Sep 2012 15:22:53 GMT Status: 401 Unauthorized Cache-Control: no-cache, max-age=300 Content-Type: application/json; charset=utf-8 WWW-Authenticate: OAuth realm="https://api.twitter.com" Set-Cookie: k=10.35.49.113.1347463372997743; path=/; expires=Wed, 19-Sep-12 15:22:52 GMT; domain=.twitter.com Set-Cookie: guest_id=v1%3A134746337300227415; domain=.twitter.com; path=/; expires=Sat, 13-Sep-2014 03:22:53 GMT Set-Cookie: dnt=; domain=.twitter.com; path=/; expires=Thu, 01-Jan-1970 00:00:00 GMT Set-Cookie: _twitter_sess=BAh7CDoPY3JlYXRlZF9hdGwrCNdgE7s5AToHaWQiJTk1Nzk5Y2NmYmJiNmJk%250AZTFmYTAxNjEwMTUyYTk3NDU0IgpmbGFzaElDOidBY3Rpb25Db250cm9sbGVy%250AOjpGbGFzaDo6Rmxhc2hIYXNoewAGOgpAdXNlZHsA--2a58c10f6992e1ab581eecf1aa0545545968ec57; domain=.twitter.com; path=/; HttpOnly Expires: Wed, 12 Sep 2012 15:27:52 GMT Vary: Accept-Encoding Content-Encoding: gzip Content-Length: 100 Server: tfe {"error":"Read-only application cannot POST","request":"\/1\/statuses\/update.json"}

**Comment by briggl** [comment]
I went into the settings for the app and changed it from READ ONLY to READ AND WRITE.
I waited a while and I am still getting the same response.
How long should it take for the change?

(Or is there something else I need to do?)

**Comment by briggl** [comment]
I figured that one out too.

After changing it to R/W, I didn't recreate the Access Token.
Once I did that it worked OK.

Thanks for your help.

**Comment by themattharris** [comment]
awesome - glad you worked it out and that things are working for you.
if that's resolved can we close this ticket out?

**Comment by briggl** [comment]
yes, sir
