### ISSUE TITLE
Twitter API 1.1

### ISSUE THREAD

**Issue by trante** [themattharris/tmhOAuth#78]
Hello,
- Will there be an update for [Twitter API 1.1](https://dev.twitter.com/docs/api/1.1/overview) soon?
  Thank you

**Comment by trante** [comment]
It seems like for following commands only "1" to "1.1" change is sufficient.
- 1.1/friendship/create
- 1.1/friendship/destroy
- 1.1/statuses_update
- 1.1/direct_messages/new
- 1.1/statuses/retweet
- 1.1/account/verify_credentials
- 1.1/users/lookup
- 1.1/followers/ids
- 1.1/friends/ids

**Comment by themattharris** [comment]
hey trante, there's a ticket on the examples repository to do this (https://github.com/themattharris/tmhOAuth-examples/issues/2) which i'll be working on in the next few days.

tmhOAuth.php itself does not require any changes to be compliant with Twitter API v1.1.

closing this ticket out as it's a duplicate of the one for the examples repository.

**Comment by trante** [comment]
Ok. Thank you very much for response.
