### ISSUE TITLE
Could not authenticate you

### ISSUE THREAD

**Issue by kemdmq** [themattharris/tmhOAuth#79]
I'm sorry for my english but isn't my native language. I've received an error when I tried to use your twitter authentication library, I make  the object with two parameter (consumer_key, consumer_secret), then I request get the authorize url, to set the oauth_token and oauth_verifier ($tmhOAuth->config), until here everything is fine, but when i try to credentials verify account  [$tmhOAuth->request('GET', $tmhOAuth->url('1/account/verify_credentials'))], it show me this: "Could not authenticate you, Code 32" and http error code is 401

**Comment by themattharris** [comment]
have you tried my example -- https://github.com/themattharris/tmhOAuth-examples/blob/master/oauth_flow.php ?
it does all of the steps needed to get an access token and secret for a user, and then verify the credentials.

let me know if the example works for you.

**Comment by kemdmq** [comment]
Yeah, it work, I was wrong in my learning, your examples working so good,
sorry for my mistake, thanks for answer me

El oct 28, 2012 7:24 p.m., "Matt Harris" notifications@github.com
escribió:

have you tried my example --
https://github.com/themattharris/tmhOAuth-examples/blob/master/oauth_flow.php?
it does all of the steps needed to get an access token and secret for a
user, and then verify the credentials.

let me know if the example works for you.

—
Reply to this email directly or view it on
GitHubhttps://github.com/themattharris/tmhOAuth/issues/79#issuecomment-9853146.

**Comment by themattharris** [comment]
glad you got it working!
i'll go ahead and close this issue out

**Comment by kemdmq** [comment]
Thanks for supporting

El oct 28, 2012 7:31 p.m., "Matt Harris" notifications@github.com
escribió:

glad you got it working!
i'll go ahead and close this issue out

—
Reply to this email directly or view it on GitHub.

[image]

**Comment by prabuguna** [comment]
@themattharris i m getting the same issue. can u enable that link which you have mentioned in top.

https://github.com/themattharris/tmhOAuthExamples

i m using this examples please let me know wat i need to do.

in this web directory oauth_authorize_flow.php works for me. others not woking.
