### ISSUE TITLE
tmhOAuth.php (65) -> curl_cainfo ISSUE

### ISSUE THREAD

**Issue by andobolocco** [themattharris/tmhOAuth#80]
'curl_cainfo'                => dirname(**FILE**) . '/cacert.pem',

should be

'curl_cainfo'                => dirname(**FILE**) . DIRECTORY_SEPARATOR . 'cacert.pem',

for windows environments.

thanks.

**Comment by themattharris** [comment]
thanks - yeah multi-environment support is a good thing. i'll get this in the next release.

**Comment by rasa** [comment]
That's not true. Windows works just fine with forward slashes.

**Comment by themattharris** [comment]
maybe, i'll still switch to the internal constant
