### ISSUE TITLE
API Version v1.1 access

### ISSUE THREAD

**Issue by robinflyhigh** [themattharris/tmhOAuth#81]
I wanted to call https://dev.twitter.com/docs/api/1.1/get/friendships/lookup api and the url to call this is http://api.twitter.com/1.1/friendships/lookup.json 

Since this was added on version 1.1 using the old Api Url give Sorry, that page does not exist with Error Code 34

So we need to change 

$this->url = strtolower("$scheme://$host");

to

$this->url = strtolower("$scheme://$host/1.1");

Simple

:)

**Comment by conradkleinespel** [comment]
Or you can just make a `$tmhOAuth->request('GET', '/1.1/uri/here')`, no?

**Comment by themattharris** [comment]
@robinflyhigh, modifying that line would make every url begin with 1.1. this would prevent the library being used for other APIs, and also prevents use of Twitter's own /oauth endpoints.

instead the correct way of doing this is how @conradkleinespel has demonstrated.
hope that helps

**Comment by robinflyhigh** [comment]
@themattharris @conradkleinespel Suggestion taken. Thanks
