### ISSUE TITLE
Add text to image upload

### ISSUE THREAD

**Issue by LeagueRivals** [themattharris/tmhOAuth#82]
I'm using the simple form for users to upload their own photos/images instead of the fixed photo/image option. Is it possible to add text area/input box for the user to add their own text with the photo/image (instead of the fixed 'Picture Time' comment)? Thanks

**Comment by themattharris** [comment]
this would be a good suggestion for https://github.com/themattharris/tmhOAuth-examples - if you open a ticket there i'll add an API v1.1 example that does this.

closing this out from this project though as the examples are a different repository.

**Comment by LeagueRivals** [comment]
Thanks Matt, I've opened a ticket on the 'example' section.
