### ISSUE TITLE
How to Direct Message using tmhOAuth.php / tmhUtilities.php

### ISSUE THREAD

**Issue by wiresfj** [themattharris/tmhOAuth#89]
Hi Guys,

firstly I'm a great believer in the self-help so its a last resort in seeking help from you.

I want to send some direct messages to a twitter user using these great functions.

I have setup a Twitter Application and got the correct tokens etc..

I can post tweets to my account and have managed to send a photo as well, so all good so far.

I would really like to send some direct messages, but I just can't work out how to do it (not for lack of trying (other half will be leaving me at this rate, I'm already getting looks...))

I'm sure its simple, so would really appreciate if someone could show me the errors in my ways.

Many thanks,
Patrick

PS Great work Matt (Thank you)

This below works great... for Tweeting to my account.

require 'tmhOAuth.php';
require 'tmhUtilities.php';

$tmhOAuth = new tmhOAuth(array(
  'consumer_key'    => '*********************_',
  'consumer_secret' => '**_********************************_',
  'user_token'      => '**_**************************_',
  'user_secret'     => '**_************************************',
));

// Set status message
$tweetMessage = "Tweeting to my Twitter account via PHP, OAuth. (new code)";

// Check for 140 characters
if(strlen($tweetMessage) <= 140)
{
    $code = $tmhOAuth->request(
    'POST', $tmhOAuth->url('1/statuses/update'), array(
    'status' => $tweetMessage
    )); 

```
printf("Code = %u",$code);
// 200 = all good
// 401 = error
if ($code == 200) echo " All OK....";
else echo " Opps Error";
```

}

**Comment by covati** [comment]
This is abstracted from an object we have wrapped around this library and I haven't tested this as it is pulled out, but it should help:

```
// Create the auth object
$authObj = new tmhOAuth(
    array(
        'consumer_key'    => $consumer_key,
        'consumer_secret' => $consumer_secret,
        'user_token'      => $user_token,
        'user_secret'     => $user_secret,
    )
);

// make the request by user_id
$response_code = $authObj->request('POST', $authObj->url("1.1/direct_messages/new"), 
    array(
        'text'    => $dm_content,
        'user_id' => $recipient_id // if by screen name, then change param to screen_name
    )
);

if ($code == 200) {
    return json_decode($response_code);
} else {
    // deal with error message
}
```

**Comment by themattharris** [comment]
@covati's example will do as you want (thanks for sharing).

this would also be a good suggestion for https://github.com/themattharris/tmhOAuth-examples - if you open a ticket there i'll add an example that does this.

closing this out from this project though as the examples are a different repository.

**Comment by covati** [comment]
@themattharris I wrote a library that wraps the raw calls within tmhOAuth to make calling twitter a little easier. Would you be interested in pulling that into your repo?
