### ISSUE TITLE
Screen name is always lowercased.

### ISSUE THREAD

**Issue by ethauvin** [themattharris/tmhOAuth#90]
In  _tmhUtilities.php_, `$value['screen_name']` always returns the screen name lowercased, regardless of the original casing.

Hope this helps,

E.

**Comment by ethauvin** [comment]
Okay, I should not say always, often though.

E.

**Comment by themattharris** [comment]
tmhUtilities uses the formatting of the screen_name as returned in the entities payload of the Twitter API. those entities come from the library twitter-text which extracts them from the original tweet - which means the formatting of the screen_name is based on how it is written in the tweet.

closing this out as this is the correct behavior of the library - namely, echo the information it's been returned by the Twitter API.
