### ISSUE TITLE
Extra HTTP Headers

### ISSUE THREAD

**Issue by tanin47** [themattharris/tmhOAuth#98]
Hi Matt,

I need to add an HTTP header, Accept, to a request. I saw the source code, and it is not supported.

Do you plan to add it? Or would you like me to add it?

**Comment by themattharris** [comment]
the library supports this, albeit a bit oddly.

```
  // create the headers
  $headers = array(
    'header-1' => 'val1',
    'header-2' => 'val2',
  );

  // load the headers for the request
  $tmhOAuth->headers = $headers;
```

**Comment by tanin47** [comment]
Thanks!

**Comment by tanin47** [comment]
Nice, Matt!
